
-- Insert categories
INSERT INTO public.categories (slug, title, description, icon, path, image_url, visible, display_order) VALUES
('journey', 'Minha Jornada', 'Semana a semana', 'BookOpen', '/jornada', '', true, 1),
('symptoms', 'Sintomas', 'Guia completo', 'AlertCircle', '/sintomas', '', true, 2),
('exercises', 'Exercícios', 'Atividades por trimestre', 'Activity', '/exercicios', '', true, 3),
('health', 'Saúde Integral', 'Corpo e mente', 'Heart', '/saude', '', true, 4),
('diary', 'Diário', 'Registros e progresso', 'BarChart3', '/diario', '', true, 5),
('assistant', 'Assistente IA', 'Tire dúvidas', 'Bot', '/assistente', '', true, 6);

-- Insert ALL 40 weeks with enriched content
INSERT INTO public.week_contents (category_id, week_number, baby_size, baby_size_comparison, baby_development, mother_changes, common_symptoms, alerts, tip, status, reviewed) VALUES
((SELECT id FROM categories WHERE slug='journey'), 1, '< 1mm', '🌰 Grão de areia', 'A fecundação acontece e o zigoto (óvulo fertilizado) começa a se dividir rapidamente em múltiplas células enquanto viaja pelas trompas de Falópio. Nesta fase, o material genético do pai e da mãe se combinam, determinando características como cor dos olhos, cabelo e sexo do bebê.', 'Você pode não sentir nada ainda, pois o corpo está apenas começando a se preparar. Os níveis hormonais estão se ajustando silenciosamente. Algumas mulheres mais atentas podem perceber uma leve sensibilidade nos seios.', '{"Nenhum sintoma perceptível"}', '{"Comece a tomar ácido fólico (400-800mcg/dia)","Pare de consumir álcool e cigarro"}', 'Comece a tomar vitaminas pré-natais o quanto antes. O ácido fólico é essencial para prevenir defeitos do tubo neural do bebê.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 2, '< 1mm', '🌰 Semente de papoula', 'O blastocisto viaja pelas trompas rumo ao útero. Ele já possui cerca de 100 células organizadas em duas camadas: uma que formará o embrião e outra que formará a placenta. A implantação no endométrio uterino começa ao final desta semana.', 'Algumas mulheres sentem leve cólica ou spotting de implantação (pequeno sangramento rosado ou marrom). Isso é completamente normal e acontece quando o embrião se fixa na parede uterina.', '{"Leve cólica","Spotting de implantação","Sensibilidade nos seios"}', '{}', 'Mantenha hidratação adequada (pelo menos 2 litros de água por dia) e evite álcool completamente. A hidratação é crucial para a formação do líquido amniótico.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 3, '1mm', '🌰 Semente de chia', 'O embrião se implanta firmemente no útero. As células começam a se diferenciar em três camadas: ectoderma (pele e sistema nervoso), mesoderma (ossos, músculos e coração) e endoderma (órgãos internos). A placenta primitiva começa a se formar.', 'Possível sensibilidade nos seios, cansaço inexplicável e alterações de humor. O hormônio hCG começa a ser produzido, o que pode causar os primeiros sinais de gravidez. Algumas mulheres sentem um gosto metálico na boca.', '{"Sensibilidade nos seios","Fadiga","Alterações de humor","Gosto metálico na boca"}', '{}', 'Descanse bastante e ouça seu corpo. Se sentir cansaço extremo, não lute contra — seu corpo está trabalhando duro para criar uma nova vida!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 4, '2mm', '🌱 Semente de gergelim', 'O coração primitivo começa a se formar e logo começará a bater! O tubo neural (futuro cérebro e medula espinhal) se desenvolve rapidamente. Os brotos dos braços e pernas começam a aparecer. O embrião tem agora o tamanho de uma semente de gergelim.', 'Enjoo matinal pode começar com força. Seios mais sensíveis e inchados. A progesterona está em alta, causando sonolência e possível constipação. Você pode notar que precisa urinar com mais frequência.', '{"Enjoo matinal","Seios sensíveis e inchados","Fadiga intensa","Constipação","Frequência urinária"}', '{"Teste de gravidez positivo!","Agende consulta com obstetra"}', 'Coma pequenas refeições ao longo do dia para aliviar enjoos. Biscoitos de água e sal antes de levantar podem ajudar muito.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 5, '3mm', '🍊 Semente de laranja', 'O coração começa a bater! É um momento mágico — cerca de 100-120 batimentos por minuto. Braços e pernas começam como pequenos brotos. O sistema circulatório primitivo está funcionando. Olhos, orelhas e boca começam a se formar.', 'Enjoos podem se intensificar significativamente. A frequência urinária aumenta devido ao útero pressionando a bexiga. Mudanças de humor são comuns pela montanha-russa hormonal. Você pode desenvolver aversão a cheiros e alimentos que antes adorava.', '{"Enjoo intenso","Frequência urinária","Mudanças de humor","Aversão a cheiros","Salivação excessiva"}', '{"Marque sua primeira consulta pré-natal","Primeiro ultrassom pode ser realizado"}', 'Gengibre (chá, balas ou biscoitos) e limão podem ajudar com enjoos. Mantenha-se hidratada mesmo que seja difícil.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 6, '6mm', '🫐 Lentilha', 'O rosto começa a se formar! Olhos e narinas aparecem como pequenas manchas escuras. O cérebro está crescendo rapidamente e as ondas cerebrais já podem ser detectadas. Os dedos das mãos começam a se formar, ainda unidos por membranas. O coração bate forte a 150 bpm.', 'Cansaço extremo é o sintoma mais comum nesta fase. Os enjoos podem estar no auge. A cintura pode começar a engrossar levemente. Emoções intensas e choro fácil são absolutamente normais.', '{"Náusea intensa","Fadiga extrema","Inchaço abdominal","Choro fácil","Dor de cabeça"}', '{}', 'Tente dormir mais cedo e tire cochilos quando possível. Não se culpe por precisar descansar — seu corpo está construindo uma placenta e um bebê!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 7, '1,3cm', '🫐 Blueberry', 'O cérebro está crescendo rapidamente, produzindo cerca de 100 neurônios por minuto! Mãos e pés se formam com pequenos dedos. O fígado começa a produzir células sanguíneas. O cordão umbilical está totalmente formado, fornecendo nutrientes e oxigênio.', 'Salivação excessiva (ptialismo) pode ser incômoda. Aversões alimentares são comuns — respeite seu corpo. Cólicas leves são normais enquanto o útero se expande. Pode surgir acne hormonal.', '{"Salivação excessiva","Aversões alimentares","Cólicas leves","Acne hormonal","Congestão nasal"}', '{}', 'Evite alimentos com odores fortes se causarem náusea. Prefira alimentos frios ou em temperatura ambiente, que têm menos cheiro.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 8, '1,6cm', '🍇 Framboesa', 'Todos os órgãos essenciais começaram a se formar — é um marco importante! O bebê se move dentro do útero, mas você ainda não sente. Os dedos dos pés se formam. As pálpebras se desenvolvem. O intestino começa a se formar dentro do cordão umbilical.', 'Útero do tamanho de uma laranja. Calças podem começar a apertar. Azia pode surgir pela primeira vez. Constipação é comum devido à progesterona que relaxa a musculatura intestinal.', '{"Roupas apertando","Enjoo","Constipação","Azia","Gases"}', '{"Primeiro ultrassom geralmente entre 8-12 semanas","Exames de sangue do primeiro trimestre"}', 'Invista em roupas confortáveis com elástico na cintura. Não precisa comprar roupas de gestante ainda — adaptações criativas funcionam bem!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 9, '2,3cm', '🍒 Azeitona', 'Os dedos das mãos e pés se separam completamente. A cauda embrionária desaparece — o bebê está parecendo mais humano! Os músculos começam a se desenvolver. O bebê pode fazer movimentos espontâneos, como flexionar braços e pernas.', 'Cintura mais grossa é notável. Humor instável é muito comum. Congestão nasal (rinite da gravidez) pode aparecer. As veias nos seios ficam mais visíveis devido ao aumento do fluxo sanguíneo.', '{"Mudanças de humor","Congestão nasal","Dor de cabeça","Veias visíveis nos seios","Inchaço leve"}', '{}', 'Pratique respiração profunda e meditação quando se sentir ansiosa. Apps de meditação guiada para gestantes podem ser muito úteis.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 10, '3cm', '🍓 Morango', 'Os ossos começam a endurecer (ossificação). As unhas dos dedos das mãos começam a crescer. O bebê agora é oficialmente chamado de feto! Todos os órgãos vitais estão formados e começam a funcionar. O diafragma se desenvolve.', 'Veias mais visíveis pela pele. O volume sanguíneo está aumentando até 50% acima do normal. Enjoos podem começar a diminuir para algumas mulheres. A energia pode começar a voltar lentamente.', '{"Veias aparentes","Cansaço diminuindo","Enjoo pode estar diminuindo","Dor ligamentar","Fome aumentando"}', '{}', 'Comece a usar protetor solar FPS 50+ diariamente para prevenir melasma (manchas de gravidez). O rosto é especialmente sensível nesta fase.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 11, '4cm', '🍋 Limão pequeno', 'O bebê pode bocejar e soluçar! Os genitais externos começam a se diferenciar, mas ainda é cedo para identificar o sexo. Os folículos de cabelo se formam. As orelhas estão quase na posição final. O bebê começa a produzir urina.', 'Enjoos começam a diminuir para muitas mulheres. A energia está voltando gradualmente! Pode aparecer azia e gases com mais frequência. O apetite pode começar a aumentar.', '{"Azia","Gases","Mais energia","Apetite aumentando","Constipação"}', '{}', 'Aproveite o retorno da energia para retomar atividades leves como caminhadas. O exercício físico moderado é excelente para a gestação!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 12, '5,4cm', '🍑 Ameixa', 'Os reflexos estão se desenvolvendo — o bebê pode fechar os punhos! O sistema digestivo pratica movimentos de contração. O rosto tem perfil mais definido. A medula óssea começa a produzir glóbulos brancos para o sistema imunológico.', 'O risco de aborto espontâneo diminui significativamente após esta semana! A barriguinha pode começar a aparecer. Muitas mulheres sentem alívio emocional ao completar o primeiro trimestre.', '{"Barriga aparecendo","Disposição melhorando","Constipação","Dor de cabeça","Inchaço leve"}', '{"Exame de translucência nucal (11-14 semanas)","NIPT pode ser oferecido","Fim do período crítico - momento de celebrar!"}', 'Esse é um momento seguro para compartilhar a novidade com família e amigos! Muitos casais esperam até agora para anunciar.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 13, '7,4cm', '🍋 Limão', 'As cordas vocais se formam (embora o bebê não vá usá-las até nascer). Os intestinos migram do cordão umbilical para o abdômen. As impressões digitais únicas estão se formando! O bebê pode chupar o polegar.', 'Bem-vinda ao 2° trimestre — geralmente o mais confortável! Mais energia e disposição. A libido pode mudar (para mais ou para menos — ambos são normais). O enjoo geralmente desaparece.', '{"Mais energia","Menos enjoo","Libido alterada","Dor ligamentar","Apetite forte"}', '{}', 'O 2° trimestre é frequentemente chamado de "lua de mel da gravidez". Aproveite para fazer coisas que gosta!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 14, '8,7cm', '🍊 Nectarina', 'O bebê faz expressões faciais — pode franzir a testa e fazer caretas! O lanugo (pelinhos finos) começa a cobrir todo o corpo para proteção. O bebê pratica respirar líquido amniótico. O timo produz células T para o sistema imunológico.', 'O apetite aumenta consideravelmente. Disposição melhora muito. Dores ligamentares (fisgadas na lateral da barriga) são comuns e normais. O cabelo pode ficar mais grosso e brilhante.', '{"Mais apetite","Dores ligamentares","Congestão nasal","Cabelo mais bonito","Desejos alimentares"}', '{}', 'Comece a hidratar a barriga, seios e coxas diariamente para prevenir estrias. Óleos naturais como amêndoas e coco são ótimas opções.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 15, '10cm', '🍎 Maçã', 'O bebê está cada vez mais ativo! Ele pode virar a cabeça, mexer as mãos e chutar. Os ossos estão ficando mais duros. As papilas gustativas estão se formando — o bebê pode "sentir" sabores do líquido amniótico.', 'A barriga está crescendo visivelmente. Pode surgir a "linha nigra" (linha escura vertical no abdômen). O nariz pode ficar mais congestionado. Energia em alta!', '{"Linha nigra aparecendo","Congestão nasal","Dores ligamentares","Inchaço leve","Mudanças na pele"}', '{}', 'Vista roupas de gestante se precisar — abraçar a barriguinha é libertador! Não se preocupe em esconder.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 16, '11,6cm', '🥑 Abacate', 'O bebê ouve sons! Os ossinhos do ouvido estão se formando. As unhas dos pés começam a crescer. O sistema nervoso está amadurecendo rapidamente. O bebê faz cerca de 200 movimentos por dia!', 'Você pode sentir as primeiras mexidas (como borboletas ou bolhas no ventre)! É um dos momentos mais emocionantes da gravidez. O útero está na metade do caminho entre o púbis e o umbigo.', '{"Primeiras mexidas","Mais energia","Nariz entupido","Desejos alimentares","Dor lombar leve"}', '{}', 'Converse e cante para o bebê — ele já pode ouvir sua voz! Coloque músicas suaves e observe se ele se mexe em resposta.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 17, '13cm', '🥕 Cenoura', 'A gordura marrom começa a se depositar sob a pele, ajudando a regular a temperatura corporal. O cordão umbilical está mais grosso e forte. O bebê desenvolve reflexo de sucção mais forte. As sobrancelhas e cílios começam a crescer.', 'O corpo se adapta ao peso extra. A postura muda naturalmente. Pode haver mais fome à noite. O sono pode ser mais leve. Você pode notar manchas na pele (melasma) se não usar protetor solar.', '{"Fome noturna","Sono mais leve","Melasma","Dor lombar","Inchaço nos pés"}', '{}', 'Mantenha lanches saudáveis à mão: castanhas, frutas, iogurte. Comer a cada 3 horas ajuda a manter a energia estável.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 18, '14cm', '🫑 Pimentão', 'O sistema digestivo do bebê está funcionando! Ele engole líquido amniótico e produz mecônio (as primeiras fezes). A mielinização dos nervos começa, permitindo movimentos mais coordenados. Se for menina, o útero e as trompas já estão formados.', 'O útero está quase na altura do umbigo. Movimentos do bebê ficam mais perceptíveis. Pode surgir tontura ao levantar rápido (hipotensão postural). O equilíbrio muda com o crescimento da barriga.', '{"Tontura ao levantar","Movimentos do bebê","Dor lombar","Cãibras noturnas","Azia"}', '{}', 'Levante-se sempre devagar da cama ou cadeira. Primeiro sente, espere alguns segundos, depois levante. Isso previne tonturas.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 19, '15cm', '🥭 Manga', 'A vernix caseosa (camada protetora cerosa) começa a cobrir a pele do bebê, protegendo-a do líquido amniótico. Os cinco sentidos estão se desenvolvendo. O bebê tem períodos regulares de sono e vigília.', 'Você pode sentir o bebê mexer com mais clareza! A pele da barriga pode começar a coçar à medida que se estica. Pode haver mais transpiração. Os seios podem começar a produzir colostro.', '{"Coceira na barriga","Transpiração","Colostro","Movimentos do bebê","Falta de ar leve"}', '{}', 'Hidrate a pele da barriga sempre após o banho. Evite água muito quente, que resseca a pele e piora a coceira.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 20, '25cm', '🍌 Banana', 'Metade da gestação! O bebê está coberto de vernix caseosa. Os movimentos ficam mais fortes e coordenados. O sistema nervoso está amadurecendo rapidamente. O bebê já tem padrões de sono regulares e pode até sonhar!', 'Barriga bem visível. O umbigo pode começar a saltar. Dor lombar aumenta com o crescimento do útero. Você pode sentir cãibras nas pernas, especialmente à noite.', '{"Dor lombar","Cãibras noturnas","Inchaço leve","Falta de ar","Azia"}', '{"Ultrassom morfológico (18-22 semanas) - exame muito importante!","Descubra o sexo do bebê (se desejar)"}', 'Use almofada entre as pernas para dormir melhor. Um travesseiro de corpo inteiro pode ser o melhor investimento da sua gravidez!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 21, '26cm', '🥕 Cenoura grande', 'O bebê engole líquido amniótico regularmente, praticando a digestão. As papilas gustativas estão funcionando — ele pode distinguir sabores doces e amargos. Os movimentos são vigorosos e você pode até ver a barriga se mexer!', 'O útero está acima do umbigo. A barriga cresce rapidamente. Estrias podem começar a aparecer. As costas sentem mais o peso. Você pode sentir o bebê reagir a sons altos.', '{"Estrias","Dor nas costas","Azia","Falta de ar leve","Inchaço"}', '{}', 'Alterne entre sentar e ficar em pé durante o dia. Evite ficar na mesma posição por mais de 1 hora.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 22, '27cm', '🌽 Espiga pequena', 'Os olhos estão formados, mas a íris ainda não tem cor. O pâncreas está amadurecendo. O bebê tem ciclos de sono-vigília bem definidos. Ele pode ouvir batimentos cardíacos da mãe, sua voz e músicas.', 'Você pode notar contrações leves e indolores (Braxton Hicks muito esporádicas). O equilíbrio muda com o crescimento da barriga. Pode haver inchaço nos pés ao final do dia.', '{"Braxton Hicks leves","Inchaço nos pés","Dor lombar","Fome constante","Esquecimento (baby brain)"}', '{}', 'Eleve os pés sempre que possível. No trabalho, use um banquinho sob a mesa. Em casa, deite com os pés apoiados em almofadas.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 23, '28cm', '🥬 Berinjela pequena', 'O rosto do bebê está quase completamente formado. Ele pratica expressões faciais o tempo todo! A pele ainda é fina e translúcida, mas está ficando mais opaca. Os pulmões começam a produzir surfactante (substância essencial para respirar após o nascimento).', 'A barriga está grande e redonda. Pode ser mais difícil amarrar os sapatos! Azia e refluxo podem intensificar. O sono pode ficar mais fragmentado. Sonhos vívidos são muito comuns.', '{"Azia intensa","Sonhos vívidos","Dificuldade para dormir","Dor nas costas","Inchaço"}', '{}', 'Para azia, evite comer 2-3 horas antes de dormir. Durma com a cabeceira elevada e evite alimentos ácidos, frituras e chocolate.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 24, '30cm', '🌽 Espiga de milho', 'Os pulmões desenvolvem surfactante ativamente. O bebê tem ciclos de sono claros e acorda com sons. Os olhos podem abrir e fechar. O rosto está completamente formado e é possível ver expressões em ultrassom 3D!', 'A linha nigra pode estar mais escura. A pele está esticando significativamente. Pode haver coceira intensa na barriga. Dor no nervo ciático pode começar.', '{"Linha nigra escura","Coceira na barriga","Estrias","Ciática","Câimbras"}', '{"Teste de glicose/curva glicêmica (24-28 semanas)","Se sentir coceira intensa generalizada, avise seu médico"}', 'Hidrate muito a pele da barriga, seios e coxas. Beba muita água e aplique óleo ou creme hidratante após cada banho.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 25, '34cm', '🥦 Couve-flor', 'O bebê ganha peso rapidamente! O cabelo pode estar crescendo. As narinas se abrem e ele pratica "respirar". A pele fica mais rosada conforme os vasos sanguíneos se formam. O bebê responde a estímulos de luz e som.', 'A barriga continua crescendo. Pode haver azia mais intensa. Cãibras nas pernas são comuns, especialmente à noite. Você pode sentir mais calor que o normal.', '{"Azia","Câimbras","Sensação de calor","Falta de ar","Insônia"}', '{}', 'Para câimbras noturnas, estique a perna e flexione o pé para cima. Aumentar a ingestão de magnésio e potássio (bananas, castanhas) pode ajudar.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 26, '35cm', '🥒 Pepino grande', 'O bebê pratica abrir e fechar os olhos. Ele pode reagir à luz forte que penetra pela barriga. Os pulmões estão mais desenvolvidos, mas ainda precisam amadurecer. O sistema imunológico está se fortalecendo com anticorpos da mãe.', 'O útero está bem acima do umbigo. Sentar e levantar pode ser desconfortável. Pode haver mais pressão na pelve. O sono é mais difícil de conseguir em posição confortável.', '{"Pressão pélvica","Insônia","Falta de ar","Azia","Inchaço"}', '{}', 'Considere fazer um curso de preparação para o parto. É o momento ideal para começar!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 27, '36cm', '🥬 Couve', 'O bebê abre os olhos completamente pela primeira vez! Ele pode distinguir luz e escuridão. O cérebro está extremamente ativo. O bebê pode ter soluços frequentes (você vai sentir!). Os pulmões continuam amadurecendo.', 'Fim do 2° trimestre! O corpo se prepara para a reta final. Pode haver mais cansaço novamente. Inchaço nos pés e mãos pode aumentar. Dor nas costas é muito comum.', '{"Cansaço aumentando","Inchaço","Dor nas costas","Soluços do bebê","Frequência urinária"}', '{"Início do acompanhamento mais frequente","Avalie opções de parto com seu médico"}', 'Comece a pesquisar sobre amamentação. Participar de grupos de apoio à amamentação antes do parto faz toda a diferença!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 28, '37cm', '🍆 Berinjela', 'O bebê abre os olhos e tem fases de sono e vigília bem definidas! Ele pode ter soluços que você sente. O cérebro desenvolve sulcos e circunvoluções. A camada de gordura aumenta, deixando a pele menos enrugada.', 'Bem-vinda ao 3° trimestre! A reta final começou. Falta de ar pode ser mais frequente. Azia pode se intensificar. As consultas médicas ficam mais frequentes agora.', '{"Falta de ar","Azia intensa","Insônia","Inchaço","Dor lombar"}', '{"Início do 3° trimestre","Consultas passam a ser quinzenais","Dose de reforço anti-D (se Rh negativo)"}', 'Durma de lado, preferencialmente o esquerdo, para melhorar a circulação. Use travesseiros de apoio para maior conforto.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 29, '38cm', '🎃 Abóbora pequena', 'O bebê está ganhando peso rapidamente — cerca de 200g por semana! Os ossos estão ficando mais duros (exceto o crânio, que permanece flexível para o parto). Os movimentos podem parecer mais "apertados" conforme o espaço diminui.', 'O útero pressiona o diafragma, causando falta de ar. Pode ser difícil comer grandes refeições. Braxton Hicks podem ser mais frequentes. O cansaço volta com força.', '{"Falta de ar","Braxton Hicks","Cansaço","Azia","Dificuldade para comer grandes refeições"}', '{}', 'Coma refeições menores e mais frequentes. O estômago está comprimido pelo útero, então porções menores são mais confortáveis.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 30, '39cm', '🥥 Coco grande', 'O bebê pratica "respirar" líquido amniótico, fortalecendo os pulmões. A medula óssea produz células sanguíneas. O lanugo começa a desaparecer. O cérebro continua se desenvolvendo rapidamente com bilhões de neurônios.', 'A barriga está muito grande. Pode ser difícil encontrar posição confortável para dormir. Dor no quadril e pelve aumenta. Você pode notar mais Braxton Hicks.', '{"Insônia","Dor no quadril","Braxton Hicks","Falta de ar","Inchaço nos pés"}', '{}', 'Pratique posições confortáveis com almofadas: uma entre as pernas, uma apoiando a barriga e uma nas costas.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 31, '41cm', '🍍 Abacaxi', 'Todos os cinco sentidos estão funcionando! O bebê pode sentir dor, ver luz, ouvir sons, provar e cheirar. Os pulmões estão quase maduros. O bebê está ficando mais rechonchudo conforme a gordura se acumula.', 'Braxton Hicks mais frequentes. Pressão pélvica intensa. Pode haver mais cansaço. Os seios podem vazar colostro. Caminhar fica mais difícil.', '{"Braxton Hicks frequentes","Pressão pélvica","Colostro vazando","Cansaço extremo","Dor lombar"}', '{"Considere fazer o plano de parto"}', 'Comece a pensar no seu plano de parto. Anote suas preferências e converse com seu médico sobre elas.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 32, '42cm', '🥥 Coco', 'O bebê está ganhando gordura e ficando mais rechonchudo. Unhas crescidas e cabelo podem estar compridos. Ele pratica respiração simulada. A posição pode começar a se definir (de cabeça para baixo na maioria dos casos).', 'Barriga muito grande. Contrações de Braxton Hicks são mais frequentes e podem ser mais perceptíveis. Dor nas costelas é comum quando o bebê chuta. O cansaço é intenso.', '{"Braxton Hicks","Pressão pélvica","Cansaço extremo","Dor nas costelas","Insônia"}', '{"Monte a mala da maternidade","Verifique a posição do bebê com seu médico"}', 'Monte a mala da maternidade! Inclua: documentos, roupas para você e bebê, itens de higiene, carregador de celular e lanches.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 33, '43cm', '🍈 Melão cantalupo', 'O bebê está quase na posição final para o nascimento. Os ossos do crânio permanecem flexíveis e separados para facilitar a passagem pelo canal de parto. O sistema imunológico está recebendo anticorpos da mãe.', 'A pressão na pelve aumenta muito. Pode haver dificuldade para andar longas distâncias. Idas frequentes ao banheiro. Braxton Hicks podem ser confundidas com contrações reais.', '{"Pressão pélvica intensa","Frequência urinária extrema","Braxton Hicks","Insônia","Dor no quadril"}', '{}', 'Aprenda a diferenciar Braxton Hicks de contrações reais: as reais são regulares, ficam mais fortes e não passam mudando de posição.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 34, '45cm', '🍈 Melão médio', 'A vernix caseosa fica mais espessa. Os pulmões estão quase completamente maduros. O bebê dorme muito — até 95% do tempo! Quando acordado, os movimentos são fortes e definidos. Ele pode reconhecer a voz da mãe.', 'O cansaço é intenso. Pode haver inchaço significativo nos pés e tornozelos. Dor nas costas é constante. O bebê pode "encaixar" na pelve, aliviando a falta de ar mas aumentando a pressão na bexiga.', '{"Cansaço extremo","Inchaço nos pés","Dor lombar constante","Insônia","Pressão na bexiga"}', '{"Consultas semanais podem começar","Monitoramento da pressão arterial"}', 'Descanse sempre que puder. Delegue tarefas quando possível. Seu corpo está se preparando para um dos maiores esforços da vida!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 35, '46cm', '🍈 Melão honeydew', 'O bebê está ganhando cerca de 200g por semana. Os rins estão completamente maduros. O fígado processa resíduos. O bebê está ficando "apertado" no útero, então os movimentos mudam de chutes para rolamentos e empurrões.', 'O útero está na altura máxima. Pode ser difícil respirar profundamente. Azia pode ser intensa. O nesting (instinto de organizar e limpar tudo) pode começar. Ansiedade sobre o parto é normal.', '{"Falta de ar intensa","Azia","Ansiedade","Nesting","Contrações de treinamento"}', '{"Certifique-se de que a cadeirinha do carro está instalada"}', 'Se sentir vontade de organizar tudo — é o instinto de nesting! Aproveite, mas não exagere no esforço físico.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 36, '47cm', '🍈 Melão', 'O bebê está se encaixando na posição de parto (geralmente de cabeça para baixo). Os pulmões estão quase maduros. A camada de gordura está completa, deixando o bebê com aspecto mais "rechonchudo". Ele pratica sucção e deglutição.', 'Pressão na bexiga é intensa — idas frequentíssimas ao banheiro. Pode respirar melhor se o bebê encaixar. Caminhar fica mais difícil. Ansiedade sobre o parto é muito comum.', '{"Pressão na bexiga extrema","Dificuldade para caminhar","Ansiedade","Braxton Hicks frequentes","Insônia"}', '{"Consultas semanais","Teste Streptococcus do Grupo B (Strep B)","Mala da maternidade deve estar pronta"}', 'Pratique técnicas de respiração para o parto todos os dias. Respiração rítmica ajuda muito durante as contrações.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 37, '48cm', '🍉 Mini melancia', 'O bebê é considerado "a termo precoce". Os pulmões estão maduros na maioria dos casos. Ele pratica respirar, sugar e engolir. O bebê ganha 14g de gordura por dia! Os intestinos acumulam mecônio.', 'O bebê pode "descer" para a pelve, causando alívio na falta de ar mas mais pressão pélvica. Tampa mucosa pode começar a sair. Braxton Hicks podem ser mais intensas e frequentes.', '{"Pressão pélvica intensa","Perda da tampa mucosa","Braxton Hicks intensas","Insônia","Ansiedade"}', '{"Atente-se a sinais de trabalho de parto","Conheça o caminho para a maternidade"}', 'Tenha o número do seu médico e da maternidade sempre à mão. Conheça o caminho e tenha um plano B de transporte.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 38, '49cm', '🍉 Melancia pequena', 'O bebê é considerado a termo! Todos os órgãos estão completamente maduros e funcionando. O cérebro e os pulmões continuam a amadurecer. O bebê pesa em média 3kg e está pronto para a vida fora do útero.', 'O instinto de nesting pode estar em alta. Tampa mucosa pode sair (sinal de que o colo está se preparando). Contrações irregulares podem acontecer. Ansiedade e excitação se misturam.', '{"Instinto de organização intensa","Ansiedade","Contrações irregulares","Insônia","Pressão pélvica"}', '{"Atente-se a sinais de trabalho de parto: contrações regulares a cada 5 minutos, ruptura da bolsa, sangramento"}', 'Sinais de trabalho de parto real: contrações regulares (a cada 5 min por 1 hora), ruptura da bolsa (líquido claro), pressão intensa e constante.', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 39, '50cm', '🍉 Melancia média', 'O bebê continua a ganhar peso e se preparar para o nascimento. O sistema imunológico recebe os últimos anticorpos da mãe através da placenta. A camada de vernix está quase toda absorvida. O bebê está totalmente pronto!', 'Pode haver mais contrações de treinamento. A ansiedade é muito normal. Cansaço extremo e dificuldade para dormir. Cada contração pode fazer você pensar "será agora?". Paciência!', '{"Contrações de treinamento","Ansiedade extrema","Insônia","Cansaço","Irritabilidade"}', '{"Se as contrações ficarem regulares, vá à maternidade","Monitore os movimentos do bebê"}', 'Tente relaxar e descansar o máximo possível. O parto pode acontecer a qualquer momento. Confie no seu corpo e na sua preparação!', 'published', true),

((SELECT id FROM categories WHERE slug='journey'), 40, '51cm', '🍉 Melancia', 'O bebê está completamente pronto para nascer! Peso médio de 3-3,5kg e cerca de 51cm. Os pulmões estão maduros. O cérebro continuará se desenvolvendo após o nascimento. A placenta está no seu tamanho máximo.', 'Você pode estar muito ansiosa — isso é completamente normal! Cada contração pode parecer "a hora". Converse com seu médico sobre os próximos passos caso não entre em trabalho de parto espontaneamente.', '{"Ansiedade extrema","Contrações","Insônia","Pressão pélvica","Impaciência"}', '{"Se passar de 41 semanas, consulte seu médico sobre indução","Monitore movimentos do bebê diariamente"}', 'Confie no seu corpo. Você se preparou durante 40 semanas para este momento! Cada mulher e cada parto é único. Você vai conseguir! 💪', 'published', true);
