
INSERT INTO symptoms (name, description, when_common, what_to_do, when_see_doctor, alert_level, trimester, category_id, display_order, active) VALUES
('Tontura e Vertigem', 'Sensação de desequilíbrio ou cabeça leve, comum pela queda de pressão arterial e aumento do volume sanguíneo.', 'Mais frequente no 1° e 2° trimestre, especialmente ao levantar rápido.', 'Levante-se devagar, mantenha-se hidratada, faça refeições pequenas e frequentes. Evite ficar em pé por longos períodos.', 'Se desmaiar, tiver visão turva persistente ou tontura intensa e frequente.', 'moderate', '{1,2}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 16, true),
('Sensibilidade e Dor nos Seios', 'Os seios ficam maiores, mais sensíveis e doloridos devido às mudanças hormonais que preparam o corpo para a amamentação.', 'Muito comum no 1° trimestre e pode retornar no 3° trimestre.', 'Use sutiãs com bom suporte e sem aro, aplique compressas mornas e evite dormir de bruços.', 'Se notar nódulos, secreção com sangue ou vermelhidão intensa em uma área.', 'low', '{1,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 17, true),
('Alterações de Humor', 'Oscilações emocionais frequentes causadas pelas mudanças hormonais, incluindo irritabilidade, choro fácil e ansiedade.', 'Mais intensas no 1° trimestre e no final do 3° trimestre.', 'Pratique autocuidado, converse com pessoas de confiança, faça atividades relaxantes e durma bem.', 'Se sentir tristeza persistente, perda de interesse em atividades, pensamentos negativos recorrentes ou ansiedade incapacitante.', 'moderate', '{1,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 18, true),
('Aumento da Frequência Urinária', 'Necessidade de urinar com mais frequência causada pela pressão do útero na bexiga e pelo aumento do fluxo sanguíneo nos rins.', 'Comum no 1° trimestre e intensifica-se no 3° trimestre quando o bebê desce.', 'Não reduza a ingestão de água. Evite cafeína, esvazie a bexiga completamente e use absorventes se necessário.', 'Se sentir dor ou ardência ao urinar, urina com sangue ou febre — pode ser infecção urinária.', 'low', '{1,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 19, true),
('Desejos e Aversões Alimentares', 'Vontade intensa de comer determinados alimentos ou repulsa por outros, relacionada às alterações hormonais.', 'Mais comuns no 1° trimestre, podendo persistir durante toda a gestação.', 'Atenda aos desejos com moderação, mantenha alimentação equilibrada e substitua alimentos que causam aversão por opções nutritivas.', 'Se tiver desejo de comer substâncias não alimentares (gelo, terra, sabão) — pode indicar deficiência nutricional.', 'low', '{1,2}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 20, true),
('Dor no Ligamento Redondo', 'Dor aguda ou pontada na parte inferior do abdômen ou virilha, causada pelo estiramento dos ligamentos que sustentam o útero.', 'Mais comum no 2° trimestre, quando o útero cresce rapidamente.', 'Mude de posição devagar, use cinto de sustentação para gestantes e descanse quando sentir dor.', 'Se a dor for constante, vier acompanhada de febre, sangramento ou contrações regulares.', 'low', '{2}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 21, true),
('Hemorroidas', 'Veias dilatadas na região anal causadas pela pressão do útero e pelo aumento do fluxo sanguíneo, podendo causar dor e sangramento.', 'Mais comuns no 2° e 3° trimestre.', 'Aumente a ingestão de fibras e água, evite ficar sentada por muito tempo e use banhos de assento mornos.', 'Se houver sangramento retal intenso, dor severa ou hemorroidas que não melhoram.', 'moderate', '{2,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 22, true),
('Varizes', 'Veias dilatadas e visíveis nas pernas causadas pelo aumento do volume sanguíneo e pela pressão do útero nas veias da pelve.', 'Mais comuns no 2° e 3° trimestre.', 'Evite ficar em pé por longos períodos, eleve as pernas quando possível, use meias de compressão e faça caminhadas leves.', 'Se uma veia ficar muito dolorida, vermelha, quente ou inchada — pode indicar trombose.', 'moderate', '{2,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 23, true),
('Coceira na Pele (Prurido)', 'Coceira no abdômen, seios e coxas causada pelo estiramento da pele e alterações hormonais.', 'Comum no 2° e 3° trimestre conforme a barriga cresce.', 'Hidrate a pele diariamente, use roupas de algodão, evite banhos muito quentes e aplique loções calmantes.', 'Se a coceira for intensa nas palmas das mãos e solas dos pés, especialmente à noite — pode indicar colestase gestacional (condição séria).', 'moderate', '{2,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 24, true),
('Dor na Pelve / Sínfise Púbica', 'Dor na região pélvica ou no osso púbico causada pelo relaxamento dos ligamentos e pelo peso do bebê.', 'Mais comum no 3° trimestre, mas pode começar no 2°.', 'Evite movimentos bruscos, use travesseiro entre as pernas ao dormir e faça exercícios de fortalecimento pélvico.', 'Se a dor impedir a locomoção ou vier acompanhada de febre ou corrimento.', 'moderate', '{2,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 25, true),
('Salivação Excessiva (Ptialismo)', 'Produção aumentada de saliva, frequentemente associada ao enjoo matinal, causada por alterações hormonais.', 'Mais comum no 1° trimestre.', 'Escove os dentes frequentemente, mastigue gelo ou balas de gengibre e cuspa o excesso se necessário.', 'Se vier acompanhada de vômitos intensos que impedem a alimentação.', 'low', '{1}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 26, true),
('Corrimento Vaginal Aumentado', 'Aumento do corrimento vaginal (leucorreia) claro ou esbranquiçado, fino e com odor leve — é normal na gravidez.', 'Presente durante toda a gestação, mais intenso no 3° trimestre.', 'Use absorventes diários, mantenha a higiene íntima com sabonete neutro e use roupas íntimas de algodão.', 'Se o corrimento tiver cor amarelada/esverdeada, odor forte, coceira ou for acompanhado de dor — pode indicar infecção.', 'low', '{1,2,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 27, true),
('Gengiva Sensível e Sangramento', 'Gengivas inchadas que sangram facilmente ao escovar os dentes, causadas pelo aumento hormonal e do fluxo sanguíneo.', 'Comum durante toda a gestação, mais perceptível no 2° trimestre.', 'Use escova de dentes macia, passe fio dental diariamente e mantenha consultas regulares ao dentista.', 'Se houver dor intensa, inchaço facial ou sinais de infecção na gengiva.', 'low', '{1,2,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 28, true),
('Síndrome do Túnel do Carpo', 'Formigamento, dormência ou dor nas mãos e dedos causados pela retenção de líquidos que pressiona o nervo mediano.', 'Mais comum no 3° trimestre.', 'Evite movimentos repetitivos, use tala noturna, faça alongamentos nas mãos e eleve os braços quando possível.', 'Se a dormência for constante, perder força na mão ou não melhorar após o parto.', 'low', '{3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 29, true),
('Dor no Nervo Ciático (Ciatalgia)', 'Dor que irradia da lombar para a nádega e perna, causada pela pressão do útero no nervo ciático.', 'Mais comum no 2° e 3° trimestre.', 'Faça alongamentos, aplique compressas quentes, evite ficar sentada por muito tempo e durma de lado com travesseiro entre as pernas.', 'Se a dor for incapacitante, vier com fraqueza na perna ou perda de sensibilidade.', 'moderate', '{2,3}', '3cbefa71-cd26-4c71-a19e-3aa236b7dba7', 30, true);
