
INSERT INTO exercises (name, description, intensity, steps, contraindications, trimester, category_id, display_order, active) VALUES
('Elevação Lateral de Pernas', 'Fortalece os músculos do quadril e glúteos, ajudando a estabilizar a pelve durante a gestação.', 'Leve', '{"Deite-se de lado com as pernas esticadas e a cabeça apoiada no braço","Levante a perna de cima lentamente até a altura do quadril","Mantenha por 3 segundos e abaixe devagar","Repita 10 vezes de cada lado","Faça 2 séries"}', 'Evite se sentir dor na pelve ou no quadril. Pare se houver desconforto.', '{1,2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 11, true),

('Ponte de Glúteo', 'Fortalece glúteos, assoalho pélvico e lombar, ajudando a aliviar dores nas costas.', 'Moderado', '{"Deite-se de costas com os joelhos dobrados e os pés apoiados no chão","Contraia os glúteos e levante o quadril do chão","Mantenha a posição por 5 segundos no topo","Desça devagar até a posição inicial","Repita 10-12 vezes, faça 2-3 séries"}', 'Evite após o 2° trimestre se sentir tontura ao deitar de costas. Use apoio com travesseiro.', '{1,2}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 12, true),

('Agachamento Sumo', 'Trabalha coxas internas, glúteos e ajuda a preparar o corpo para o parto, melhorando a flexibilidade do quadril.', 'Moderado', '{"Fique em pé com os pés mais abertos que os ombros e pontas dos pés para fora","Segure-se em uma cadeira ou parede para apoio","Desça lentamente dobrando os joelhos, mantendo as costas retas","Vá até onde for confortável, sem ultrapassar os joelhos além dos pés","Suba devagar. Repita 8-10 vezes, 2 séries"}', 'Evite se tiver dor pélvica intensa ou instabilidade articular. Use sempre um apoio.', '{2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 13, true),

('Alongamento de Panturrilha', 'Ajuda a prevenir cãibras nas pernas, muito comuns durante a gravidez, especialmente à noite.', 'Leve', '{"Fique em pé de frente para uma parede, com as mãos apoiadas","Dê um passo para trás com uma perna, mantendo-a esticada","Flexione o joelho da frente até sentir o alongamento na panturrilha de trás","Mantenha por 20-30 segundos","Troque de perna. Repita 3 vezes cada lado"}', 'Nenhuma contraindicação. Seguro em todas as fases da gestação.', '{1,2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 14, true),

('Rotação de Tronco Sentada', 'Melhora a mobilidade da coluna e alivia tensão nas costas, mantendo a flexibilidade do tronco.', 'Leve', '{"Sente-se em uma cadeira com os pés apoiados no chão","Coloque as mãos no peito ou atrás da cabeça","Gire o tronco lentamente para um lado, olhando por cima do ombro","Mantenha por 10 segundos e volte ao centro","Repita para o outro lado. Faça 5 rotações para cada lado"}', 'Faça movimentos suaves e lentos. Evite girar com força.', '{1,2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 15, true),

('Inclinação Pélvica (Pelvic Tilt)', 'Alivia dor lombar e fortalece os músculos abdominais profundos, preparando o corpo para o parto.', 'Leve', '{"Fique de quatro apoios (mãos e joelhos)","Inspire e relaxe a barriga em direção ao chão","Expire e contraia o abdômen, arredondando levemente as costas","Mantenha a contração por 5 segundos","Repita 10-15 vezes"}', 'Nenhuma contraindicação. Pode ser feito em qualquer fase da gestação.', '{1,2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 16, true),

('Exercício de Braço com Peso Leve', 'Fortalece braços e ombros para preparar o corpo para carregar e amamentar o bebê.', 'Moderado', '{"Use pesos leves (0,5-1kg) ou garrafas de água","Fique em pé com os braços ao lado do corpo","Faça flexão de bíceps: levante os pesos até os ombros e desça devagar","Faça elevação lateral: levante os braços abertos até a altura dos ombros","Repita 10-12 vezes cada exercício, 2 séries"}', 'Use pesos leves. Evite prender a respiração. Pare se sentir tontura.', '{1,2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 17, true),

('Postura da Criança (Balasana)', 'Posição de descanso do yoga que alonga a lombar, alivia tensão e promove relaxamento profundo.', 'Leve', '{"Ajoelhe-se no chão com os joelhos afastados","Sente-se sobre os calcanhares (ou use almofada)","Incline o tronco para frente, estendendo os braços à frente","Abra os joelhos para acomodar a barriga","Descanse a testa no chão e respire profundamente por 1-2 minutos"}', 'No 3° trimestre, abra bem os joelhos para dar espaço à barriga. Evite se sentir desconforto.', '{1,2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 18, true),

('Dança Suave / Movimento Livre', 'Atividade aeróbica leve que melhora o humor, a circulação e a conexão com o corpo durante a gestação.', 'Leve', '{"Escolha uma música calma e agradável","Fique em pé com os pés afastados na largura dos ombros","Movimente o quadril em círculos suaves","Balance os braços e mova o corpo livremente","Faça movimentos de 10-15 minutos, respeitando seu ritmo"}', 'Evite movimentos bruscos, saltos ou giros rápidos. Mantenha o equilíbrio.', '{1,2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 19, true),

('Exercício de Respiração para o Parto', 'Técnicas de respiração que ajudam no controle da dor e ansiedade durante o trabalho de parto.', 'Leve', '{"Sente-se confortavelmente ou deite de lado","Pratique respiração lenta: inspire em 4 tempos pelo nariz, expire em 6 tempos pela boca","Pratique respiração rápida (para contrações): inspire curto pelo nariz e sopre pela boca rapidamente","Pratique respiração de sopro: como se estivesse apagando uma vela, para a fase expulsiva","Treine cada padrão por 2-3 minutos diariamente"}', 'Nenhuma contraindicação. Pode ser praticado diariamente em qualquer fase.', '{2,3}', 'af8304a8-9cfa-4202-adf6-a300a000fa2e', 20, true);
