
-- Add day_of_week to weekly_tips
ALTER TABLE weekly_tips ADD COLUMN IF NOT EXISTS day_of_week integer NOT NULL DEFAULT 1;

-- Add image_url and description to health_tips
ALTER TABLE health_tips ADD COLUMN IF NOT EXISTS image_url text NOT NULL DEFAULT '';
ALTER TABLE health_tips ADD COLUMN IF NOT EXISTS description text NOT NULL DEFAULT '';

-- Insert 280 daily tips for the entire pregnancy journey
INSERT INTO weekly_tips (week_number, day_of_week, title, content, active, display_order) VALUES
-- Week 1
(1,1,'Início da contagem','A gestação é contada a partir do 1º dia da última menstruação. Sua jornada começou!',true,1),
(1,2,'Ácido fólico','Comece a tomar ácido fólico (400mcg/dia). Previne defeitos no tubo neural do bebê.',true,2),
(1,3,'Alimentação saudável','Inclua frutas, verduras e proteínas magras em todas as refeições.',true,3),
(1,4,'Hidratação','Beba ao menos 2 litros de água por dia para manter o corpo bem hidratado.',true,4),
(1,5,'Evite álcool','Elimine bebidas alcoólicas completamente durante a gestação.',true,5),
(1,6,'Sono reparador','Durma entre 7 e 9 horas por noite. O descanso é fundamental agora.',true,6),
(1,7,'Exercícios leves','Caminhadas leves de 20 minutos ajudam a manter o corpo ativo.',true,7),
-- Week 2
(2,1,'Ovulação','Seu corpo está se preparando para a ovulação e possível fecundação.',true,1),
(2,2,'Vitaminas pré-natais','Além do ácido fólico, considere um complexo vitamínico pré-natal.',true,2),
(2,3,'Reduza cafeína','Limite o consumo de cafeína a no máximo 200mg por dia (1 xícara de café).',true,3),
(2,4,'Ferro na dieta','Feijão, lentilha e espinafre são ótimas fontes de ferro.',true,4),
(2,5,'Peso saudável','Manter um peso saudável antes da gravidez facilita toda a gestação.',true,5),
(2,6,'Evite cigarro','O tabagismo prejudica a fertilidade e o desenvolvimento do bebê.',true,6),
(2,7,'Relax','Pratique técnicas de relaxamento como respiração profunda.',true,7),
-- Week 3
(3,1,'Fecundação','O óvulo pode ser fecundado nesta semana. Um novo ser pode estar se formando!',true,1),
(3,2,'Cálcio','Consuma leite, queijo e iogurte para garantir cálcio suficiente.',true,2),
(3,3,'Evite medicamentos','Não tome medicamentos sem orientação médica.',true,3),
(3,4,'Ômega 3','Peixes como sardinha e salmão são ricos em ômega 3, ótimo para o cérebro do bebê.',true,4),
(3,5,'Sono tranquilo','Evite telas 1 hora antes de dormir para melhorar a qualidade do sono.',true,5),
(3,6,'Fibras','Cereais integrais e frutas com casca ajudam o funcionamento intestinal.',true,6),
(3,7,'Positividade','Mantenha pensamentos positivos. Seu estado emocional influencia seu corpo.',true,7),
-- Week 4
(4,1,'Teste positivo?','Se sua menstruação atrasou, faça um teste de gravidez!',true,1),
(4,2,'Primeiro pré-natal','Agende sua primeira consulta pré-natal o quanto antes.',true,2),
(4,3,'Enjoo matinal','Enjoos podem começar. Coma biscoitos secos antes de levantar.',true,3),
(4,4,'Embrião','Seu bebê tem o tamanho de uma semente de papoula!',true,4),
(4,5,'Descanso','É normal sentir muito cansaço. Respeite os sinais do seu corpo.',true,5),
(4,6,'Compartilhe','Escolha o momento certo para contar a novidade ao parceiro(a).',true,6),
(4,7,'Diário','Comece um diário da gestação para registrar cada momento especial.',true,7),
-- Week 5
(5,1,'Coração batendo','O coraçãozinho do seu bebê começa a bater nesta semana!',true,1),
(5,2,'Gengibre','Chá de gengibre pode aliviar as náuseas matinais naturalmente.',true,2),
(5,3,'Pequenas refeições','Coma de 5 a 6 refeições pequenas ao longo do dia.',true,3),
(5,4,'Sensibilidade','Seios sensíveis são normais. Use sutiãs confortáveis de algodão.',true,4),
(5,5,'Vitamina D','Tome sol por 15 minutos pela manhã para absorver vitamina D.',true,5),
(5,6,'Emoções','Oscilações de humor são normais devido às mudanças hormonais.',true,6),
(5,7,'Parceiro(a)','Inclua seu parceiro(a) desde o início. A gestação é de vocês dois!',true,7),
-- Week 6
(6,1,'Formação dos órgãos','Os principais órgãos do bebê começam a se formar agora.',true,1),
(6,2,'Evite frios','Evite alimentos crus ou mal cozidos para prevenir toxoplasmose.',true,2),
(6,3,'Zinco','Castanhas e sementes são ricas em zinco, importante para o desenvolvimento.',true,3),
(6,4,'Exames','Realize os exames de sangue solicitados pelo médico sem atraso.',true,4),
(6,5,'Alongamento','Alongue-se gentilmente ao acordar para aliviar tensões no corpo.',true,5),
(6,6,'Água de coco','Água de coco é hidratante e rica em minerais essenciais.',true,6),
(6,7,'Gratidão','Reserve um momento do dia para agradecer pela vida que cresce em você.',true,7),
-- Week 7
(7,1,'Rosto formando','O rostinho do bebê começa a ganhar forma com olhos e nariz.',true,1),
(7,2,'Proteínas','Consuma proteínas em todas as refeições: ovos, frango, peixe ou leguminosas.',true,2),
(7,3,'Náusea persistente','Se os enjoos forem intensos, converse com seu médico sobre opções.',true,3),
(7,4,'Caminhada','20 minutos de caminhada diária melhoram circulação e humor.',true,4),
(7,5,'Hidrate a pele','Use cremes hidratantes na barriga e seios para prevenir estrias.',true,5),
(7,6,'Música','Ouça músicas relaxantes. O bebê já pode perceber vibrações!',true,6),
(7,7,'Vitamina C','Laranja, acerola e kiwi ajudam na absorção do ferro.',true,7),
-- Week 8
(8,1,'Dedos se formando','Os dedinhos do bebê começam a se separar nesta semana!',true,1),
(8,2,'Evite queijos macios','Queijos não pasteurizados podem conter listeria. Prefira pasteurizados.',true,2),
(8,3,'Fadiga','A fadiga extrema do 1º trimestre é temporária. Logo passará!',true,3),
(8,4,'Respiração','Pratique respiração diafragmática por 5 minutos ao dia.',true,4),
(8,5,'Frutas vermelhas','Morango, mirtilo e framboesa são ricos em antioxidantes.',true,5),
(8,6,'Ultrassom','Sua primeira ultrassonografia pode acontecer em breve!',true,6),
(8,7,'Conexão','Converse com seu bebê. Ele já está crescendo e se desenvolvendo.',true,7),
-- Week 9
(9,1,'Movimentos','O bebê começa a fazer pequenos movimentos, mesmo que você não sinta.',true,1),
(9,2,'Cuidado dental','Agende uma consulta ao dentista. A saúde bucal é importante na gestação.',true,2),
(9,3,'Abacate','Abacate é rico em gorduras boas e ácido fólico natural.',true,3),
(9,4,'Roupas confortáveis','Comece a usar roupas mais largas e confortáveis.',true,4),
(9,5,'Evite toxinas','Evite produtos de limpeza fortes e ambientes com tintas.',true,5),
(9,6,'Meditação','5 minutos de meditação guiada ajudam a reduzir ansiedade.',true,6),
(9,7,'Magnésio','Banana, abacate e chocolate amargo são fontes de magnésio.',true,7),
-- Week 10
(10,1,'Fase fetal','Seu bebê oficialmente entra na fase fetal. Todos os órgãos estão formados!',true,1),
(10,2,'Constipação','Aumente o consumo de fibras e água para evitar prisão de ventre.',true,2),
(10,3,'Ioga prenatal','Ioga para gestantes ajuda na flexibilidade e no relaxamento.',true,3),
(10,4,'Batata doce','Rica em vitamina A e fibras, excelente para a gestação.',true,4),
(10,5,'Trabalho','Planeje como e quando comunicar a gravidez no trabalho.',true,5),
(10,6,'Autoestima','Seu corpo está mudando por um motivo lindo. Orgulhe-se!',true,6),
(10,7,'Ferro','Continue atenta ao ferro. A anemia gestacional é comum e tratável.',true,7),
-- Week 11
(11,1,'Unhas crescendo','As unhas do bebê começam a crescer nesta semana!',true,1),
(11,2,'Probióticos','Iogurte natural e kefir ajudam a manter a flora intestinal saudável.',true,2),
(11,3,'Postura','Mantenha boa postura ao sentar. Use apoio para as costas.',true,3),
(11,4,'Chá de camomila','Camomila é segura com moderação e ajuda a relaxar.',true,4),
(11,5,'Planejamento','Comece a pesquisar sobre o enxoval do bebê.',true,5),
(11,6,'Sucos naturais','Prefira sucos naturais sem açúcar adicionado.',true,6),
(11,7,'Momento de paz','Reserve 10 minutos do dia só para você, em silêncio.',true,7),
-- Week 12
(12,1,'Fim do 1º trimestre','Parabéns! Você está completando o primeiro trimestre!',true,1),
(12,2,'Translucência nucal','A ultrassom de translucência nucal é realizada entre as semanas 11-14.',true,2),
(12,3,'Energia voltando','A partir de agora, sua energia tende a melhorar gradualmente.',true,3),
(12,4,'Vitamina B6','Grão-de-bico e banana são ricos em B6, que ajuda contra enjoos.',true,4),
(12,5,'Celebre','Comemore essa conquista! O primeiro trimestre pode ser desafiador.',true,5),
(12,6,'Pele','Algumas gestantes notam o "brilho da gravidez" na pele agora.',true,6),
(12,7,'Contar a novidade','Muitas mamães escolhem este momento para anunciar a gravidez.',true,7),
-- Week 13
(13,1,'Segundo trimestre','Bem-vinda ao segundo trimestre! A fase mais confortável da gestação.',true,1),
(13,2,'Impressão digital','As impressões digitais do bebê já estão se formando!',true,2),
(13,3,'Apetite','Seu apetite pode aumentar. Escolha alimentos nutritivos.',true,3),
(13,4,'Pilates','Pilates para gestantes fortalece o assoalho pélvico.',true,4),
(13,5,'Linea nigra','Uma linha escura pode aparecer na barriga. É normal e temporária.',true,5),
(13,6,'Leitura','Leia sobre parto e amamentação para se sentir mais preparada.',true,6),
(13,7,'Hidratação da pele','Aplique óleo de amêndoas na barriga após o banho.',true,7),
-- Week 14
(14,1,'Expressões faciais','O bebê já consegue fazer expressões faciais como franzir a testa!',true,1),
(14,2,'Protetor solar','Use protetor solar diariamente para prevenir melasma gestacional.',true,2),
(14,3,'Dentista','Mantenha a saúde bucal em dia. Gengivite é mais comum na gravidez.',true,3),
(14,4,'Quinoa','Quinoa é um superalimento rico em proteínas e minerais.',true,4),
(14,5,'Dor lombar','Evite ficar de pé por longos períodos para prevenir dor nas costas.',true,5),
(14,6,'Sonhar com o bebê','É comum sonhar mais vividamente na gravidez. Anote seus sonhos!',true,6),
(14,7,'Gratidão','Escreva 3 coisas pelas quais é grata hoje.',true,7),
-- Week 15
(15,1,'Audição','O bebê começa a ouvir sons! Converse e cante para ele.',true,1),
(15,2,'Aveia','Aveia no café da manhã fornece energia e fibras para o dia.',true,2),
(15,3,'Exercícios de Kegel','Fortaleça o assoalho pélvico com exercícios de Kegel diários.',true,3),
(15,4,'Roupas de gestante','Invista em algumas peças confortáveis de roupa para gestantes.',true,4),
(15,5,'Sono lateral','Comece a se acostumar a dormir de lado, preferencialmente o esquerdo.',true,5),
(15,6,'Fotografias','Tire fotos da barriga mensalmente para registrar a evolução.',true,6),
(15,7,'Vitamina E','Sementes de girassol e amêndoas são ricas em vitamina E.',true,7),
-- Week 16
(16,1,'Sexo do bebê','Em breve você poderá descobrir o sexo do bebê na ultrassom!',true,1),
(16,2,'Cãibras','Cãibras nas pernas são comuns. Alongue antes de dormir.',true,2),
(16,3,'Brócolis','Brócolis é rico em cálcio, ferro e ácido fólico. Inclua no cardápio!',true,3),
(16,4,'Vínculo','Acaricie sua barriga. O bebê pode sentir o toque!',true,4),
(16,5,'Água aromatizada','Adicione frutas à água para tornar a hidratação mais prazerosa.',true,5),
(16,6,'Planejamento financeiro','Comece a organizar as finanças para a chegada do bebê.',true,6),
(16,7,'Caminhada na natureza','Caminhar em áreas verdes reduz o estresse e melhora o humor.',true,7),
-- Week 17
(17,1,'Gordura marrom','O bebê começa a acumular gordura, essencial para regulação térmica.',true,1),
(17,2,'Congestão nasal','Congestão nasal é comum na gravidez. Use soro fisiológico.',true,2),
(17,3,'Espinafre','Rico em ferro e folato, o espinafre é aliado da gestante.',true,3),
(17,4,'Chá de folha de framboesa','Pode ajudar a tonificar o útero. Consulte seu médico antes.',true,4),
(17,5,'Sapatos confortáveis','Use sapatos com bom suporte. Seus pés podem inchar.',true,5),
(17,6,'Rede de apoio','Fortaleça sua rede de apoio: família, amigos e profissionais.',true,6),
(17,7,'Colágeno','Frutas cítricas estimulam a produção natural de colágeno.',true,7),
-- Week 18
(18,1,'Bocejar','O bebê já boceja dentro da barriga! Adorável, não?',true,1),
(18,2,'Soluço fetal','É possível sentir o bebê soluçando. São movimentos rítmicos!',true,2),
(18,3,'Lentilha','Rica em ferro e proteína vegetal. Ótima para sopas e saladas.',true,3),
(18,4,'Massagem','Peça uma massagem relaxante ao parceiro(a) no final do dia.',true,4),
(18,5,'Cinto de segurança','Use o cinto de segurança abaixo da barriga, nunca sobre ela.',true,5),
(18,6,'Playlist do bebê','Crie uma playlist especial para ouvir durante a gestação.',true,6),
(18,7,'Nozes','Um punhado de nozes por dia fornece ômega 3 e energia.',true,7),
-- Week 19
(19,1,'Vernix caseosa','O bebê é coberto por uma camada protetora chamada vernix.',true,1),
(19,2,'Azia','Azia pode aparecer. Evite alimentos gordurosos e deite com a cabeça elevada.',true,2),
(19,3,'Salmão grelhado','Salmão é uma das melhores fontes de DHA para o cérebro do bebê.',true,3),
(19,4,'Banho morno','Banhos mornos (não quentes) ajudam a relaxar os músculos.',true,4),
(19,5,'Lista de nomes','Já começou a pensar em nomes? Faça uma lista com o parceiro(a)!',true,5),
(19,6,'Chá verde','Limite o chá verde a 1 xícara por dia devido à cafeína.',true,6),
(19,7,'Autocompaixão','Seja gentil consigo mesma. Você está fazendo um trabalho incrível!',true,7),
-- Week 20
(20,1,'Metade da gestação!','Parabéns! Você atingiu a metade da gravidez! 🎉',true,1),
(20,2,'Morfológica','A ultrassom morfológica é geralmente realizada nesta semana.',true,2),
(20,3,'Movimentos claros','Os movimentos do bebê ficam mais perceptíveis agora.',true,3),
(20,4,'Granola caseira','Granola com frutas secas é um lanche nutritivo e prático.',true,4),
(20,5,'Travesseiro de gestante','Um travesseiro entre as pernas melhora muito o sono.',true,5),
(20,6,'Carta ao bebê','Escreva uma carta para o seu bebê ler quando crescer.',true,6),
(20,7,'Vitamina K','Vegetais verde-escuros fornecem vitamina K para coagulação saudável.',true,7),
-- Week 21
(21,1,'Paladar','O bebê já consegue sentir sabores do líquido amniótico!',true,1),
(21,2,'Inchaço','Elevação dos pés ao final do dia reduz o inchaço nas pernas.',true,2),
(21,3,'Grão-de-bico','Hummus é delicioso e rico em proteínas e fibras.',true,3),
(21,4,'Natação','Natação é um dos melhores exercícios para gestantes.',true,4),
(21,5,'Prevenção de estrias','Continue hidratando a pele diariamente, sem pular nenhum dia.',true,5),
(21,6,'Conexão em casal','Reservem um tempo para curtir a dois antes do bebê chegar.',true,6),
(21,7,'Frutas da estação','Prefira frutas da estação: mais nutritivas e econômicas.',true,7),
-- Week 22
(22,1,'Sobrancelhas','O bebê já tem sobrancelhas formadas, mas sem pigmentação!',true,1),
(22,2,'Contrações de Braxton Hicks','Contrações leves de "treinamento" podem começar. São normais.',true,2),
(22,3,'Tomate','Rico em licopeno e vitamina C. Inclua em molhos e saladas.',true,3),
(22,4,'Posição para dormir','Durma do lado esquerdo para melhor circulação ao bebê.',true,4),
(22,5,'Curso de gestantes','Procure cursos de preparação para o parto na sua cidade.',true,5),
(22,6,'Mindfulness','3 minutos de atenção plena por dia reduzem a ansiedade.',true,6),
(22,7,'Selênio','Castanha-do-pará (2 por dia) fornece selênio suficiente.',true,7),
-- Week 23
(23,1,'Audição aguçada','O bebê reage a sons altos e pode se assustar!',true,1),
(23,2,'Tonturas','Levante-se devagar para evitar tonturas por queda de pressão.',true,2),
(23,3,'Feijão preto','Excelente fonte de ferro, proteína e fibras. Inclua no cardápio!',true,3),
(23,4,'Alongamento suave','Alongue pescoço, ombros e costas para aliviar tensões.',true,4),
(23,5,'Enxoval','Comece a montar a lista do enxoval do bebê.',true,5),
(23,6,'Aromaterapia','Lavanda pode ajudar a relaxar. Use em difusores ou travesseiro.',true,6),
(23,7,'Potássio','Banana e melão são ricos em potássio, ajudam contra cãibras.',true,7),
-- Week 24
(24,1,'Viabilidade','O bebê atinge o marco de viabilidade fetal! Grande conquista!',true,1),
(24,2,'Teste de glicose','O teste de tolerância à glicose costuma ser feito entre as semanas 24-28.',true,2),
(24,3,'Cenoura','Cenoura é rica em betacaroteno, que se converte em vitamina A.',true,3),
(24,4,'Dança','Dançar suavemente é divertido e bom exercício para gestantes!',true,4),
(24,5,'Quarto do bebê','Comece a planejar a decoração do quarto do bebê.',true,5),
(24,6,'Diário do bebê','Registre os horários em que sente o bebê se mexer.',true,6),
(24,7,'Cobre','Sementes de abóbora são ricas em cobre e zinco.',true,7),
-- Week 25
(25,1,'Ciclo de sono','O bebê já tem ciclos de sono e vigília definidos.',true,1),
(25,2,'Dor ciática','Se sentir dor no nervo ciático, aplique compressas mornas.',true,2),
(25,3,'Ovo cozido','Rico em proteína e colina, essencial para o cérebro do bebê.',true,3),
(25,4,'Respiração para o parto','Comece a praticar técnicas de respiração para o trabalho de parto.',true,4),
(25,5,'Pediatra','Pesquise e escolha o pediatra do seu bebê com antecedência.',true,5),
(25,6,'Banho de sol seguro','15 minutos de sol da manhã para vitamina D. Use protetor no rosto!',true,6),
(25,7,'Fósforo','Leite e derivados são ótimas fontes de fósforo para ossos fortes.',true,7),
-- Week 26
(26,1,'Olhos se abrindo','O bebê abre os olhinhos pela primeira vez nesta semana!',true,1),
(26,2,'Roupas do bebê','Lave as roupinhas do bebê com sabão neutro antes do uso.',true,2),
(26,3,'Beterraba','Rica em ferro e folato. Ótima em sucos com laranja e cenoura.',true,3),
(26,4,'Exercícios pélvicos','Continue os exercícios de Kegel para fortalecer a região pélvica.',true,4),
(26,5,'Plano de parto','Comece a pensar no seu plano de parto e tire dúvidas com o médico.',true,5),
(26,6,'Momento a dois','Aproveitem para assistir filmes juntos e curtir a fase.',true,6),
(26,7,'Iodo','Sal iodado e peixes marinhos garantem iodo para a tireoide.',true,7),
-- Week 27
(27,1,'Soluços frequentes','O bebê soluça frequentemente, praticando a respiração!',true,1),
(27,2,'Fim do 2º trimestre','Você está finalizando o segundo trimestre. Faltam 13 semanas!',true,2),
(27,3,'Manga','Rica em vitaminas A e C, a manga é uma fruta deliciosa para gestantes.',true,3),
(27,4,'Caminhada leve','Mantenha caminhadas diárias de 15-20 minutos.',true,4),
(27,5,'Mala da maternidade','Comece a separar itens para a mala da maternidade.',true,5),
(27,6,'Affirmations','Repita afirmações positivas: "Meu corpo sabe parir".',true,6),
(27,7,'Zinco e imunidade','Zinco ajuda a manter seu sistema imunológico forte.',true,7),
-- Week 28
(28,1,'Terceiro trimestre!','Bem-vinda ao terceiro e último trimestre! A reta final!',true,1),
(28,2,'Contagem de movimentos','Comece a contar os movimentos do bebê: 10 em 2 horas é o ideal.',true,2),
(28,3,'Iogurte grego','Rico em proteína e probióticos. Ótimo lanche para gestantes.',true,3),
(28,4,'Vacinação','Confirme com seu médico se suas vacinas estão em dia (dTpa, gripe).',true,4),
(28,5,'Anti-Rh','Se você é Rh negativo, a injeção de imunoglobulina é feita agora.',true,5),
(28,6,'Conversa com o bebê','Conte ao bebê sobre sua família. Ele reconhece sua voz!',true,6),
(28,7,'Vitamina B12','Carnes, ovos e leite garantem B12 para o sistema nervoso.',true,7),
-- Week 29
(29,1,'Espaço apertado','O bebê está crescendo rápido e o espaço fica mais apertado!',true,1),
(29,2,'Falta de ar','Falta de ar leve é normal. O útero pressiona o diafragma.',true,2),
(29,3,'Sardinha','Rica em ômega 3 e cálcio (nos ossinhos). Excelente opção!',true,3),
(29,4,'Relaxamento muscular','Tensione e relaxe cada grupo muscular por 5 segundos.',true,4),
(29,5,'Berço e enxoval','Verifique se o berço e o enxoval básico já estão providenciados.',true,5),
(29,6,'Empatia consigo','Não se cobre demais. Cada gestação é única e tem seu ritmo.',true,6),
(29,7,'Biotina','Ovos e nozes fornecem biotina para cabelos e unhas saudáveis.',true,7),
-- Week 30
(30,1,'2,5 kg estimados','O bebê pesa aproximadamente 1,3 kg e mede cerca de 40 cm!',true,1),
(30,2,'Insônia','Insônia é comum no 3º trimestre. Crie uma rotina de sono relaxante.',true,2),
(30,3,'Abóbora','Rica em betacaroteno e fibras. Ótima em sopas e purês.',true,3),
(30,4,'Posições de parto','Pesquise diferentes posições para o trabalho de parto.',true,4),
(30,5,'Cadeirinha do carro','Pesquise e compre a cadeirinha de bebê para o carro.',true,5),
(30,6,'Fotografia gestacional','Que tal fazer um ensaio fotográfico de gestante?',true,6),
(30,7,'Manganês','Abacaxi e grãos integrais são fontes de manganês.',true,7),
-- Week 31
(31,1,'Cérebro em expansão','O cérebro do bebê está em rápido desenvolvimento!',true,1),
(31,2,'Síndrome do túnel do carpo','Formigamento nas mãos pode ocorrer. Eleve os braços periodicamente.',true,2),
(31,3,'Tahine','Pasta de gergelim é rica em cálcio e ferro.',true,3),
(31,4,'Bola de pilates','Sentar na bola de pilates ajuda a aliviar dores nas costas.',true,4),
(31,5,'Documentos','Deixe documentos do hospital e plano de saúde organizados.',true,5),
(31,6,'Ninho do bebê','O instinto de nidificação pode aparecer. Aproveite a energia!',true,6),
(31,7,'Cromo','Brócolis e carne bovina ajudam a regular a glicose no sangue.',true,7),
-- Week 32
(32,1,'Posição cefálica','Muitos bebês já estão de cabeça para baixo nesta semana!',true,1),
(32,2,'Hemorroidas','Coma fibras, beba água e evite ficar sentada por muito tempo.',true,2),
(32,3,'Melancia','Hidratante e rica em licopeno. Ótima para o verão!',true,3),
(32,4,'Técnica de visualização','Visualize um parto tranquilo e positivo todos os dias.',true,4),
(32,5,'Lista do hospital','Finalize a lista de itens para levar à maternidade.',true,5),
(32,6,'Chá de bebê','Se ainda não fez, organize o chá de bebê ou revelação!',true,6),
(32,7,'Ácidos graxos','Azeite de oliva extravirgem é fonte de gorduras saudáveis.',true,7),
-- Week 33
(33,1,'Imunidade transferida','Seus anticorpos estão sendo transferidos ao bebê agora.',true,1),
(33,2,'Xixi frequente','A pressão na bexiga aumenta. Não segure a urina!',true,2),
(33,3,'Mamão papaia','Rico em fibras e vitamina C. Ajuda no funcionamento intestinal.',true,3),
(33,4,'Massagem perineal','A massagem perineal pode ajudar na preparação para o parto.',true,4),
(33,5,'Telefones importantes','Salve telefones do hospital, obstetra e transporte emergencial.',true,5),
(33,6,'Nana para o bebê','Escolha uma canção para cantar ao seu bebê todas as noites.',true,6),
(33,7,'Vitamina A','Cenoura e manga são ricas em vitamina A para visão e imunidade.',true,7),
-- Week 34
(34,1,'Pulmões amadurecendo','Os pulmões do bebê estão quase prontos para respirar!',true,1),
(34,2,'Edema','Inchaço nos pés e mãos é normal, mas avise o médico se for intenso.',true,2),
(34,3,'Aveia com frutas','Aveia com banana e mel é um café da manhã perfeito.',true,3),
(34,4,'Caminhada estratégica','Caminhar ajuda o bebê a descer e se encaixar na pelve.',true,4),
(34,5,'Mala pronta','Deixe a mala da maternidade pronta a partir de agora!',true,5),
(34,6,'Carta de amor','Escreva uma carta de amor para sua barriga.',true,6),
(34,7,'DHA','DHA é essencial para o desenvolvimento cerebral. Peixes e suplementos.',true,7),
-- Week 35
(35,1,'2,5 kg!','O bebê pesa cerca de 2,5 kg e está cada vez mais gordinho!',true,1),
(35,2,'Consultas semanais','As consultas pré-natais agora podem ser semanais.',true,2),
(35,3,'Oleaginosas','Um mix de castanhas, nozes e amêndoas é um lanche perfeito.',true,3),
(35,4,'Streptococcus B','O exame de Streptococcus B é realizado entre as semanas 35-37.',true,4),
(35,5,'Licença maternidade','Confirme os detalhes da sua licença maternidade.',true,5),
(35,6,'Rede de apoio pós-parto','Organize quem vai ajudar nos primeiros dias após o nascimento.',true,6),
(35,7,'Triptofano','Leite morno antes de dormir contém triptofano e ajuda no sono.',true,7),
-- Week 36
(36,1,'Encaixe pélvico','O bebê começa a "encaixar" na pelve para o parto.',true,1),
(36,2,'Tampão mucoso','A perda do tampão mucoso pode ocorrer nas próximas semanas.',true,2),
(36,3,'Sopa nutritiva','Sopas com legumes e proteínas são reconfortantes e nutritivas.',true,3),
(36,4,'Sinais de trabalho de parto','Aprenda a diferenciar contrações reais das de treinamento.',true,4),
(36,5,'Checklist final','Revise: mala, cadeirinha, documentos, números de emergência.',true,5),
(36,6,'Momento de paz','Medite por 10 minutos visualizando o encontro com seu bebê.',true,6),
(36,7,'Colostro','Seu corpo já pode estar produzindo colostro. É o primeiro leite!',true,7),
-- Week 37
(37,1,'Termo precoce','Seu bebê é considerado termo precoce. Pode nascer a qualquer momento!',true,1),
(37,2,'Nesting','O instinto de organizar tudo é forte agora. Aproveite!',true,2),
(37,3,'Tâmaras','Estudos sugerem que comer tâmaras pode facilitar o trabalho de parto.',true,3),
(37,4,'Bolsa estourar','Saiba o que fazer se a bolsa romper: ligue para o médico e vá ao hospital.',true,4),
(37,5,'Carrinho e berço','Verifique se carrinho e berço estão montados e prontos.',true,5),
(37,6,'Agradecimento','Agradeça ao seu corpo por essa jornada incrível.',true,6),
(37,7,'Amamentação','Informe-se sobre técnicas de amamentação e pega correta.',true,7),
-- Week 38
(38,1,'Pronto para nascer','O bebê está totalmente desenvolvido e pronto para o mundo!',true,1),
(38,2,'Sinais de parto','Fique atenta a contrações regulares e perda de líquido.',true,2),
(38,3,'Frutas frescas','Mantenha frutas frescas à mão para lanches rápidos e saudáveis.',true,3),
(38,4,'Caminhada curta','Continue caminhando se se sentir confortável.',true,4),
(38,5,'Acompanhante','Confirme quem será seu acompanhante no parto. É seu direito!',true,5),
(38,6,'Visualização do parto','Imagine o primeiro choro, o primeiro toque. Está chegando!',true,6),
(38,7,'Descanso','Descanse o máximo possível. Logo suas noites serão bem agitadas!',true,7),
-- Week 39
(39,1,'Reflexos prontos','O bebê tem reflexos de sucção e preensão totalmente prontos.',true,1),
(39,2,'Paciência','Cada dia conta. O bebê virá no momento certo.',true,2),
(39,3,'Chocolate amargo','Um quadradinho de chocolate amargo (70%+) melhora o humor!',true,3),
(39,4,'Bolsa na porta','Deixe a mala do hospital junto à porta, pronta para sair.',true,4),
(39,5,'Playlist do parto','Prepare uma playlist relaxante para ouvir durante o trabalho de parto.',true,5),
(39,6,'Confiança','Confie no seu corpo. Ele foi feito para isso.',true,6),
(39,7,'Últimos preparativos','Congele refeições prontas para os primeiros dias pós-parto.',true,7),
-- Week 40
(40,1,'Data provável!','Hoje é a data provável do parto! Mas o bebê decide quando chegar.',true,1),
(40,2,'Paciência final','Apenas 5% dos bebês nascem na data prevista. Relaxe!',true,2),
(40,3,'Refeições leves','Prefira refeições leves e frequentes para manter a energia.',true,3),
(40,4,'Movimento pélvico','Movimentos circulares na bola de pilates ajudam no encaixe.',true,4),
(40,5,'Equipe pronta','Confirme que sua equipe médica está de plantão e acessível.',true,5),
(40,6,'Você é incrível','Você completou 40 semanas! Você é uma guerreira! 💪',true,6),
(40,7,'O grande dia','A espera está acabando. Em breve você terá seu bebê nos braços! ❤️',true,7);
