
-- Fix baby size comparisons to be accurate (comparisons are by overall size/weight, not just length)
UPDATE public.week_contents SET baby_size_comparison = '🌰 Grão de areia' WHERE week_number = 1;
UPDATE public.week_contents SET baby_size_comparison = '🌰 Semente de papoula' WHERE week_number = 2;
UPDATE public.week_contents SET baby_size_comparison = '🌰 Semente de chia' WHERE week_number = 3;
UPDATE public.week_contents SET baby_size_comparison = '🌱 Semente de gergelim' WHERE week_number = 4;
UPDATE public.week_contents SET baby_size_comparison = '🫘 Grão de lentilha' WHERE week_number = 5;
UPDATE public.week_contents SET baby_size_comparison = '🫐 Ervilha' WHERE week_number = 6;
UPDATE public.week_contents SET baby_size_comparison = '🫐 Mirtilo' WHERE week_number = 7;
UPDATE public.week_contents SET baby_size_comparison = '🍇 Framboesa' WHERE week_number = 8;
UPDATE public.week_contents SET baby_size_comparison = '🫒 Azeitona' WHERE week_number = 9;
UPDATE public.week_contents SET baby_size_comparison = '🍓 Morango' WHERE week_number = 10;
UPDATE public.week_contents SET baby_size_comparison = '🍋 Figo' WHERE week_number = 11;
UPDATE public.week_contents SET baby_size_comparison = '🍑 Ameixa' WHERE week_number = 12;
UPDATE public.week_contents SET baby_size_comparison = '🍋 Limão' WHERE week_number = 13;
UPDATE public.week_contents SET baby_size_comparison = '🍊 Pêssego' WHERE week_number = 14;
UPDATE public.week_contents SET baby_size_comparison = '🍎 Maçã' WHERE week_number = 15;
UPDATE public.week_contents SET baby_size_comparison = '🥑 Abacate' WHERE week_number = 16;
UPDATE public.week_contents SET baby_size_comparison = '🍐 Pera' WHERE week_number = 17;
UPDATE public.week_contents SET baby_size_comparison = '🫑 Pimentão' WHERE week_number = 18;
UPDATE public.week_contents SET baby_size_comparison = '🥭 Manga' WHERE week_number = 19;
UPDATE public.week_contents SET baby_size_comparison = '🍌 Banana' WHERE week_number = 20;
UPDATE public.week_contents SET baby_size_comparison = '🥕 Cenoura' WHERE week_number = 21;
UPDATE public.week_contents SET baby_size_comparison = '🌽 Espiga de milho' WHERE week_number = 22;
UPDATE public.week_contents SET baby_size_comparison = '🥭 Manga grande' WHERE week_number = 23;
UPDATE public.week_contents SET baby_size_comparison = '🌽 Milho grande' WHERE week_number = 24;
UPDATE public.week_contents SET baby_size_comparison = '🥦 Couve-flor' WHERE week_number = 25;
UPDATE public.week_contents SET baby_size_comparison = '🥬 Alface' WHERE week_number = 26;
UPDATE public.week_contents SET baby_size_comparison = '🥒 Pepino' WHERE week_number = 27;
UPDATE public.week_contents SET baby_size_comparison = '🍆 Berinjela' WHERE week_number = 28;
UPDATE public.week_contents SET baby_size_comparison = '🎃 Abóbora butternut' WHERE week_number = 29;
UPDATE public.week_contents SET baby_size_comparison = '🥬 Repolho' WHERE week_number = 30;
UPDATE public.week_contents SET baby_size_comparison = '🥥 Coco' WHERE week_number = 31;
UPDATE public.week_contents SET baby_size = '43cm', baby_size_comparison = '🍍 Abacaxi' WHERE week_number = 32;
UPDATE public.week_contents SET baby_size_comparison = '🍈 Melão cantalupo' WHERE week_number = 33;
UPDATE public.week_contents SET baby_size_comparison = '🍈 Melão' WHERE week_number = 34;
UPDATE public.week_contents SET baby_size_comparison = '🍈 Melão honeydew' WHERE week_number = 35;
UPDATE public.week_contents SET baby_size_comparison = '🥬 Alface romana' WHERE week_number = 36;
UPDATE public.week_contents SET baby_size_comparison = '🎃 Abóbora' WHERE week_number = 37;
UPDATE public.week_contents SET baby_size_comparison = '🍉 Mini melancia' WHERE week_number = 38;
UPDATE public.week_contents SET baby_size_comparison = '🍉 Melancia pequena' WHERE week_number = 39;
UPDATE public.week_contents SET baby_size_comparison = '🍉 Melancia' WHERE week_number = 40;
