
UPDATE public.week_contents SET baby_size = '—', baby_size_comparison = 'Ainda não há embrião formado' WHERE week_number = 1;
UPDATE public.week_contents SET baby_size = '—', baby_size_comparison = 'Corpo se preparando para a gestação' WHERE week_number = 2;
UPDATE public.week_contents SET baby_size = '0,1 cm', baby_size_comparison = 'Grão de areia' WHERE week_number = 3;
UPDATE public.week_contents SET baby_size = '0,2 cm', baby_size_comparison = 'Grão de papoula' WHERE week_number = 4;
UPDATE public.week_contents SET baby_size = '0,4 cm', baby_size_comparison = 'Grão de gergelim' WHERE week_number = 5;
UPDATE public.week_contents SET baby_size = '0,6 cm', baby_size_comparison = 'Grão de arroz' WHERE week_number = 6;
UPDATE public.week_contents SET baby_size = '1,3 cm', baby_size_comparison = 'Grão de milho' WHERE week_number = 7;
UPDATE public.week_contents SET baby_size = '1,6 cm', baby_size_comparison = 'Feijão pequeno' WHERE week_number = 8;
UPDATE public.week_contents SET baby_size = '2,3 cm', baby_size_comparison = 'Jaboticaba pequena' WHERE week_number = 9;
UPDATE public.week_contents SET baby_size = '3,1 cm', baby_size_comparison = 'Ciriguela' WHERE week_number = 10;
UPDATE public.week_contents SET baby_size = '4,1 cm', baby_size_comparison = 'Ameixa pequena' WHERE week_number = 11;
UPDATE public.week_contents SET baby_size = '5,4 cm', baby_size_comparison = 'Limão pequeno' WHERE week_number = 12;
UPDATE public.week_contents SET baby_size = '7,4 cm', baby_size_comparison = 'Pêssego pequeno' WHERE week_number = 13;
UPDATE public.week_contents SET baby_size = '8,7 cm', baby_size_comparison = 'Maçã pequena' WHERE week_number = 14;
UPDATE public.week_contents SET baby_size = '10,1 cm', baby_size_comparison = 'Maçã média' WHERE week_number = 15;
UPDATE public.week_contents SET baby_size = '11,6 cm', baby_size_comparison = 'Abacate' WHERE week_number = 16;
UPDATE public.week_contents SET baby_size = '13 cm', baby_size_comparison = 'Pera' WHERE week_number = 17;
UPDATE public.week_contents SET baby_size = '14,2 cm', baby_size_comparison = 'Pimentão' WHERE week_number = 18;
UPDATE public.week_contents SET baby_size = '15,3 cm', baby_size_comparison = 'Manga' WHERE week_number = 19;
UPDATE public.week_contents SET baby_size = '16,4 cm', baby_size_comparison = 'Banana' WHERE week_number = 20;
UPDATE public.week_contents SET baby_size = '26,7 cm', baby_size_comparison = 'Cenoura grande' WHERE week_number = 21;
UPDATE public.week_contents SET baby_size = '27,8 cm', baby_size_comparison = 'Espiga de milho' WHERE week_number = 22;
UPDATE public.week_contents SET baby_size = '28,9 cm', baby_size_comparison = 'Berinjela' WHERE week_number = 23;
UPDATE public.week_contents SET baby_size = '30 cm', baby_size_comparison = 'Régua escolar' WHERE week_number = 24;
UPDATE public.week_contents SET baby_size = '34,6 cm', baby_size_comparison = 'Espiga de milho grande' WHERE week_number = 25;
UPDATE public.week_contents SET baby_size = '35,6 cm', baby_size_comparison = 'Pepino grande' WHERE week_number = 26;
UPDATE public.week_contents SET baby_size = '36,6 cm', baby_size_comparison = 'Abobrinha grande' WHERE week_number = 27;
UPDATE public.week_contents SET baby_size = '37,6 cm', baby_size_comparison = 'Colher grande de cozinha' WHERE week_number = 28;
UPDATE public.week_contents SET baby_size = '38,6 cm', baby_size_comparison = 'Garrafa PET 2L' WHERE week_number = 29;
UPDATE public.week_contents SET baby_size = '39,9 cm', baby_size_comparison = 'Melão grande' WHERE week_number = 30;
UPDATE public.week_contents SET baby_size = '41,1 cm', baby_size_comparison = 'Abóbora alongada' WHERE week_number = 31;
UPDATE public.week_contents SET baby_size = '42,4 cm', baby_size_comparison = 'Melancia pequena oblonga' WHERE week_number = 32;
UPDATE public.week_contents SET baby_size = '43,7 cm', baby_size_comparison = 'Abacaxi inteiro' WHERE week_number = 33;
UPDATE public.week_contents SET baby_size = '45 cm', baby_size_comparison = 'Jaca pequena' WHERE week_number = 34;
UPDATE public.week_contents SET baby_size = '46,2 cm', baby_size_comparison = 'Jaca média' WHERE week_number = 35;
UPDATE public.week_contents SET baby_size = '47,4 cm', baby_size_comparison = 'Melancia média' WHERE week_number = 36;
UPDATE public.week_contents SET baby_size = '48,6 cm', baby_size_comparison = 'Abóbora grande' WHERE week_number = 37;
UPDATE public.week_contents SET baby_size = '49,8 cm', baby_size_comparison = 'Jaca grande' WHERE week_number = 38;
UPDATE public.week_contents SET baby_size = '50,7 cm', baby_size_comparison = 'Melancia grande' WHERE week_number = 39;
UPDATE public.week_contents SET baby_size = '51,2 cm', baby_size_comparison = 'Jaca grande madura' WHERE week_number = 40;
