
-- Enriched symptoms (15 items)
INSERT INTO public.symptoms (category_id, name, description, when_common, when_see_doctor, what_to_do, alert_level, trimester, display_order) VALUES
((SELECT id FROM categories WHERE slug='symptoms'), 'Enjoo / Náusea', 'Sensação de desconforto no estômago, podendo variar de leve mal-estar a vômitos frequentes. Afeta até 80% das gestantes. Causada pelo aumento do hormônio hCG e alterações no metabolismo.', 'Semanas 4-14, mais forte pela manhã (mas pode ocorrer a qualquer hora)', 'Se não conseguir manter líquidos por 24h, perder mais de 5% do peso, ou apresentar sinais de desidratação (urina escura, tontura)', 'Coma pequenas refeições a cada 2-3h, gengibre (chá, balas ou cápsulas), biscoitos secos antes de levantar, evite estômago vazio, acupressura no ponto P6 (pulseira anti-enjoo)', 'low', '{1}', 1),
((SELECT id FROM categories WHERE slug='symptoms'), 'Fadiga / Cansaço Extremo', 'Cansaço intenso que não melhora com repouso habitual. O corpo está usando enormes quantidades de energia para construir a placenta e sustentar o crescimento do bebê. A progesterona elevada também contribui para a sonolência.', '1° trimestre (semanas 4-12) e 3° trimestre (semanas 28-40)', 'Se acompanhada de falta de ar intensa, tontura frequente, palidez extrema ou palpitações (pode indicar anemia)', 'Descanse sempre que possível, durma mais cedo, alimente-se bem com refeições ricas em ferro e proteínas, tire cochilos de 20-30min, reduza compromissos não essenciais', 'low', '{1,3}', 2),
((SELECT id FROM categories WHERE slug='symptoms'), 'Dor nas Costas / Lombar', 'Dor na região lombar e/ou nas costas causada pelo peso extra, mudança no centro de gravidade e relaxamento dos ligamentos pela relaxina. Afeta 50-70% das gestantes.', 'A partir do 2° trimestre, intensificando no 3°', 'Se a dor for intensa e constante, acompanhada de sangramento, febre, ou dormência/fraqueza nas pernas', 'Use almofadas de apoio, faça alongamentos diários (cat-cow), evite sapatos de salto, fortaleça a musculatura com exercícios leves, aplique compressas mornas, considere fisioterapia', 'low', '{2,3}', 3),
((SELECT id FROM categories WHERE slug='symptoms'), 'Azia e Refluxo', 'Queimação no estômago e esôfago causada pela progesterona que relaxa o esfíncter esofágico, e pelo útero que pressiona o estômago. Muito comum especialmente após as refeições.', '2° e 3° trimestres, piorando à medida que a barriga cresce', 'Se não melhorar com mudanças alimentares, causar dificuldade para engolir ou dor intensa no peito', 'Evite alimentos ácidos, gordurosos, café e chocolate. Coma devagar e em porções menores. Não deite logo após comer (espere 2-3h). Durma com cabeceira elevada. Iogurte e leite frios podem aliviar.', 'low', '{2,3}', 4),
((SELECT id FROM categories WHERE slug='symptoms'), 'Inchaço (Edema)', 'Retenção de líquidos nos pés, tornozelos, mãos e rosto. Causada pelo aumento do volume sanguíneo (50% a mais!) e pela pressão do útero nas veias, dificultando o retorno venoso.', '3° trimestre, pior no final do dia e em dias quentes', 'Se o inchaço for SÚBITO (em horas), especialmente no rosto e mãos, ou acompanhado de dor de cabeça intensa, visão turva ou dor abdominal (pode indicar pré-eclâmpsia)', 'Eleve os pés sempre que possível, beba bastante água (paradoxalmente ajuda!), evite ficar muito tempo em pé ou sentada, use meias de compressão, reduza sal na alimentação, faça caminhadas leves', 'moderate', '{3}', 5),
((SELECT id FROM categories WHERE slug='symptoms'), 'Contrações de Braxton Hicks', 'Contrações irregulares de "treinamento" do útero, que se prepara para o parto. São indolores ou levemente desconfortáveis, irregulares e geralmente param quando você muda de posição ou descansa.', 'A partir da semana 28, mais frequentes próximo ao parto', 'Se ficarem REGULARES (a cada 5 minutos por 1 hora), dolorosas e progressivamente mais fortes, ou antes de 37 semanas (pode ser trabalho de parto prematuro)', 'Mude de posição, beba água (desidratação pode intensificá-las), tome banho morno, pratique respiração profunda. Cronometre: se forem irregulares e pararem, são Braxton Hicks.', 'moderate', '{3}', 6),
((SELECT id FROM categories WHERE slug='symptoms'), 'Sangramento Vaginal', 'QUALQUER sangramento vaginal durante a gravidez precisa ser avaliado por um médico. No 1° trimestre pode ser implantação (normal) ou ameaça de aborto. No 2°/3° pode indicar placenta prévia ou descolamento.', 'Spotting de implantação (semanas 2-4) pode ser normal. Qualquer outro sangramento precisa de avaliação.', 'SEMPRE consulte seu médico imediatamente em caso de sangramento, especialmente se acompanhado de dor, cólicas intensas ou febre', 'Repouso absoluto e contato IMEDIATO com seu médico ou vá à emergência. Anote a cor, quantidade e se há coágulos para informar o médico.', 'high', '{1,2,3}', 7),
((SELECT id FROM categories WHERE slug='symptoms'), 'Dor de Cabeça', 'Dores de cabeça frequentes causadas por alterações hormonais, aumento do volume sanguíneo, fadiga, estresse e mudanças posturais. Mais comuns no 1° trimestre.', '1° trimestre (ajuste hormonal) e pode ocorrer no 3° trimestre', 'Se intensa e persistente, acompanhada de visão turva, manchas luminosas, inchaço no rosto ou pressão alta (pode indicar pré-eclâmpsia)', 'Descanse em ambiente escuro e silencioso, hidrate-se bem, compressa fria na testa, evite gatilhos (luz forte, barulho), faça pausas de tela, pratique respiração profunda', 'low', '{1,2}', 8),
((SELECT id FROM categories WHERE slug='symptoms'), 'Cólicas Abdominais', 'Dores abdominais semelhantes a cólicas menstruais. Podem ser causadas pela implantação do embrião, crescimento do útero ou distensão dos ligamentos redondos.', 'Início da gravidez (implantação) e 3° trimestre (ligamentos e contrações)', 'Se intensas e persistentes, acompanhadas de sangramento, febre, ou localizadas de um lado só (pode indicar gravidez ectópica)', 'Repouso, banho morno, posição confortável, bolsa de água morna no local, evitar movimentos bruscos. Leve laxante caso seja constipação.', 'moderate', '{1,3}', 9),
((SELECT id FROM categories WHERE slug='symptoms'), 'Insônia', 'Dificuldade para adormecer ou manter o sono durante a noite. Causada por desconforto físico, ansiedade, frequência urinária, movimentos do bebê e alterações hormonais.', '3° trimestre (semanas 28-40), mas pode ocorrer em qualquer fase', 'Se causar exaustão extrema que afete seu funcionamento diário, ou se acompanhada de apneia do sono', 'Rotina de sono consistente, ambiente escuro e fresco, chá de camomila, travesseiro de corpo, evitar telas 1h antes, meditação guiada, sons de natureza', 'low', '{3}', 10),
((SELECT id FROM categories WHERE slug='symptoms'), 'Constipação', 'Dificuldade para evacuar causada pela progesterona que relaxa a musculatura intestinal, e pela suplementação de ferro. Muito comum e desconfortável, mas tratável.', 'Pode ocorrer em qualquer trimestre, mais comum no 1° e 3°', 'Se não evacuar por mais de 5 dias, se houver sangue nas fezes, ou dor abdominal intensa', 'Aumente a ingestão de fibras (frutas, verduras, grãos integrais), beba muita água (2-3L/dia), faça caminhadas diárias, coma ameixas secas e mamão papaia, evite alimentos que prendem (banana-prata, goiaba)', 'low', '{1,2,3}', 11),
((SELECT id FROM categories WHERE slug='symptoms'), 'Cãibras nas Pernas', 'Contrações involuntárias e dolorosas nos músculos das pernas, especialmente na panturrilha. Mais comuns à noite. Podem estar relacionadas a deficiência de magnésio, cálcio ou desidratação.', '2° e 3° trimestres, especialmente à noite', 'Se forem muito frequentes, acompanhadas de inchaço ou vermelhidão em uma perna (pode indicar trombose)', 'Ao sentir: estique a perna e flexione o pé para cima. Prevenção: alongamentos antes de dormir, bananas e castanhas na dieta, hidratação adequada, magnésio (consulte seu médico)', 'low', '{2,3}', 12),
((SELECT id FROM categories WHERE slug='symptoms'), 'Congestão Nasal (Rinite da Gravidez)', 'Nariz entupido, coriza e espirros causados pelo aumento do fluxo sanguíneo e inchaço das mucosas nasais. Não é infecção — é uma resposta hormonal. Afeta até 30% das gestantes.', 'Pode começar no 1° trimestre e persistir até o parto', 'Se acompanhada de febre, dor facial intensa (sinusite) ou secreção amarela/verde espessa', 'Use soro fisiológico para lavagem nasal, umidifique o ambiente, durma com a cabeceira elevada, evite ambientes com ar-condicionado muito seco, vapor de água quente antes de dormir', 'low', '{1,2,3}', 13),
((SELECT id FROM categories WHERE slug='symptoms'), 'Falta de Ar (Dispneia)', 'Sensação de não conseguir respirar profundamente. No início, é causada pela progesterona que altera o padrão respiratório. No final, é o útero pressionando o diafragma.', 'Pode ocorrer em qualquer trimestre, mais intensa no 3°', 'Se for súbita e intensa, acompanhada de dor no peito, tosse com sangue ou lábios/dedos azulados (emergência!)', 'Mantenha boa postura, durma com cabeceira elevada, evite esforços intensos, pratique respiração diafragmática, use roupas que não apertem o tórax', 'moderate', '{2,3}', 14),
((SELECT id FROM categories WHERE slug='symptoms'), 'Estrias', 'Linhas avermelhadas ou rosadas na pele causadas pelo estiramento rápido da pele. Podem aparecer na barriga, seios, quadris e coxas. Fatores genéticos influenciam muito. Após um tempo ficam esbranquiçadas.', '2° e 3° trimestres, quando a barriga cresce mais rapidamente', 'Estrias não requerem atenção médica urgente, mas se incomodam, converse com dermatologista após o parto', 'Hidrate a pele 2x ao dia (manhã e noite) com óleos naturais (amêndoas, coco, rosa mosqueta) ou cremes com vitamina E. Beba muita água. Ganho de peso gradual também ajuda.', 'low', '{2,3}', 15);

-- Enriched exercises (10 items)
INSERT INTO public.exercises (category_id, name, description, steps, intensity, contraindications, trimester, display_order) VALUES
((SELECT id FROM categories WHERE slug='exercises'), 'Respiração Diafragmática', 'Exercício fundamental de respiração profunda para relaxamento, oxigenação e preparação para o parto. Ajuda a reduzir ansiedade, melhora a circulação e prepara a gestante para controlar a respiração durante as contrações.', '{"Deite-se confortavelmente ou sente-se com as costas apoiadas","Coloque uma mão no peito e outra na barriga","Inspire lentamente pelo nariz por 4 segundos, expandindo a barriga","Segure a respiração por 2 segundos","Expire pela boca lentamente por 6 segundos, sentindo a barriga contrair","A mão no peito deve se mover minimamente","Repita 10-15 vezes, 2-3x ao dia"}', 'Leve', 'Nenhuma contraindicação. Seguro em todas as fases da gestação.', '{1,2,3}', 1),
((SELECT id FROM categories WHERE slug='exercises'), 'Caminhada Leve', 'Caminhada em ritmo confortável para manter a circulação sanguínea, prevenir inchaço, melhorar o humor e a disposição. É o exercício mais recomendado durante toda a gestação.', '{"Use calçado confortável e com bom suporte","Escolha terreno plano e seguro","Comece com 10 minutos e aumente gradualmente","Mantenha ritmo conversacional (conseguir falar sem ficar ofegante)","15-30 minutos por sessão, 3-5x por semana","Leve água e lanche leve","Evite horários de calor intenso","Pare se sentir dor, tontura ou contrações"}', 'Leve', 'Restrição médica de atividade física, sangramento, placenta prévia, cerclagem, risco de parto prematuro. Sempre consulte seu médico antes.', '{1,2,3}', 2),
((SELECT id FROM categories WHERE slug='exercises'), 'Alongamento Cat-Cow (Gato-Vaca)', 'Sequência de alongamento que alivia dores nas costas e lombar, melhora a flexibilidade da coluna e ajuda a posicionar o bebê. Excelente para alívio imediato de desconforto.', '{"Fique de quatro apoios (mãos e joelhos no chão)","Mãos alinhadas com os ombros, joelhos com os quadris","GATO: Inspire e arqueie as costas para CIMA, queixo no peito","Segure 3-5 segundos","VACA: Expire e deixe a barriga pender, olhando para cima","Segure 3-5 segundos","Alterne lentamente entre as duas posições","Repita 10 vezes, 2x ao dia"}', 'Leve', 'Dor aguda na lombar, síndrome do túnel do carpo (pressão nos punhos). Use antebraços como apoio se os punhos doírem.', '{1,2,3}', 3),
((SELECT id FROM categories WHERE slug='exercises'), 'Agachamento com Apoio na Parede', 'Fortalece quadríceps, glúteos e músculos pélvicos, preparando o corpo para o parto. O agachamento é uma das posições mais naturais para o nascimento e fortalece os músculos necessários.', '{"Apoie as costas em uma parede lisa","Pés afastados na largura dos quadris, 30cm à frente da parede","Deslize as costas pela parede, descendo lentamente","Desça até 90° (nunca ultrapasse — as coxas ficam paralelas ao chão)","Segure a posição por 5-10 segundos","Suba lentamente empurrando a parede com as costas","Repita 8-10 vezes, 2-3 séries","Descanse 30 segundos entre séries"}', 'Moderado', 'Problemas nos joelhos, pressão alta não controlada, placenta prévia, restrição médica de esforço. Pare se sentir tontura.', '{2,3}', 4),
((SELECT id FROM categories WHERE slug='exercises'), 'Exercício de Kegel', 'Fortalece o assoalho pélvico, essencial para sustentar o útero, bexiga e intestino. Previne incontinência urinária, facilita o parto vaginal e acelera a recuperação pós-parto.', '{"Sente-se ou deite confortavelmente","Identifique os músculos: imagine que está segurando a urina","Contraia esses músculos (sem contrair glúteos ou abdômen)","Segure a contração por 5 segundos","Relaxe completamente por 5 segundos","Repita 10-15 vezes = 1 série","Faça 3 séries ao dia (manhã, tarde e noite)","Progresso: aumente para 10 segundos de contração"}', 'Leve', 'Nenhuma contraindicação. Pode ser feito em qualquer posição e a qualquer momento do dia, inclusive durante atividades cotidianas.', '{1,2,3}', 5),
((SELECT id FROM categories WHERE slug='exercises'), 'Yoga Pré-natal', 'Combinação de posturas suaves, respiração e meditação que melhoram flexibilidade, equilíbrio, força e conexão com o bebê. Reduz estresse e prepara corpo e mente para o parto.', '{"Postura da Criança Modificada: joelhos afastados, braços estendidos à frente","Guerreiro II Suave: pernas afastadas, braços abertos, joelho flexionado","Borboleta Sentada: solas dos pés juntas, movimentos suaves das pernas","Postura do Triângulo Modificada com apoio","Mantenha cada postura 30-45 segundos","Foque na respiração consciente","Sessão de 20-30 minutos","Termine com relaxamento em posição lateral"}', 'Leve', 'Evite posturas invertidas e deitada de barriga para cima após 20 semanas. Evite torções profundas e posturas que comprimam o abdômen. Evite Bikram/Hot Yoga.', '{1,2,3}', 6),
((SELECT id FROM categories WHERE slug='exercises'), 'Natação / Hidroginástica', 'Exercício de baixo impacto na água que alivia o peso da barriga, melhora a circulação, reduz inchaço e fortalece todo o corpo. A água sustenta o peso, permitindo movimentos livres e confortáveis.', '{"Procure uma piscina aquecida (28-30°C)","Comece com 15 minutos e aumente para 30-45min","Faça movimentos de braços e pernas na água","Caminhada na água é excelente","Evite saltos e mergulhos","Mantenha-se hidratada (sim, mesmo na água!)","2-3 sessões por semana","Prefira horários com menos pessoas na piscina"}', 'Leve', 'Evite se a bolsa estiver rompida, se houver infecções vaginais ativas, ou pressão alta não controlada. Consulte seu médico.', '{1,2,3}', 7),
((SELECT id FROM categories WHERE slug='exercises'), 'Exercícios com Bola Suíça', 'A bola de pilates ajuda a aliviar dores nas costas, treinar o equilíbrio pélvico e preparar para o parto. Sentar na bola trabalha a musculatura profunda automaticamente.', '{"Sente-se na bola com os pés apoiados no chão","Faça movimentos circulares com o quadril (10x cada lado)","Balance para frente e para trás suavemente","Faça movimentos de 8 (oito) com o quadril","Inclinações laterais suaves","Quique levemente para cima e para baixo","15-20 minutos por sessão","Use a bola também como assento no dia a dia"}', 'Moderado', 'Instabilidade ou problemas de equilíbrio. Tenha sempre um apoio por perto. Evite se houver risco de queda. Use bola do tamanho adequado (65-75cm para maioria das gestantes).', '{2,3}', 8),
((SELECT id FROM categories WHERE slug='exercises'), 'Alongamento de Quadril (Borboleta)', 'Abre a pelve e alonga os músculos internos da coxa, preparando o corpo para o parto. Ajuda a aliviar tensão no quadril e melhora a circulação na região pélvica.', '{"Sente-se no chão com as costas retas (use almofada se precisar)","Junte as solas dos pés à sua frente","Segure os pés com as mãos","Deixe os joelhos caírem suavemente para os lados","NÃO force — deixe a gravidade fazer o trabalho","Faça movimentos suaves com os joelhos (como asas de borboleta)","Mantenha por 30-60 segundos","Repita 3-5 vezes"}', 'Leve', 'Dor na sínfise púbica (separação do púbis). Se sentir dor, reduza a amplitude do movimento ou pare o exercício.', '{2,3}', 9),
((SELECT id FROM categories WHERE slug='exercises'), 'Massagem Perineal', 'Técnica de automassagem que ajuda a preparar o períneo para o parto vaginal, aumentando a elasticidade dos tecidos e reduzindo o risco de lacerações. Recomendada a partir de 34 semanas.', '{"Lave bem as mãos e corte as unhas","Use óleo vegetal (amêndoas, coco ou azeite)","Insira o polegar 3-4cm na vagina","Pressione para baixo e para os lados, em forma de U","Mantenha a pressão por 1-2 minutos","Massageie lateralmente por 3-5 minutos","Faça respiração profunda durante o procedimento","Repita diariamente a partir da semana 34"}', 'Leve', 'Infecções vaginais ativas, placenta prévia, sangramento, risco de parto prematuro. Consulte seu médico antes de iniciar.', '{3}', 10);

-- Enriched health tips
INSERT INTO public.health_tips (category_id, section_title, icon, tips, display_order) VALUES
((SELECT id FROM categories WHERE slug='health'), 'Alimentação', 'Apple', '{"Coma de 5-6 refeições pequenas por dia para manter energia e evitar enjoos","Aumente a ingestão de ferro (carnes, feijão, lentilha) e ácido fólico (vegetais verde-escuros)","Beba pelo menos 2-3L de água por dia — a hidratação é crucial para a formação do líquido amniótico","Evite alimentos crus, mal cozidos, queijos não pasteurizados e peixes com alto teor de mercúrio","Inclua ômega-3 na dieta (salmão, sardinha, nozes, linhaça) para o desenvolvimento cerebral do bebê","Frutas e verduras variadas fornecem vitaminas e fibras essenciais","Prefira carboidratos integrais (arroz integral, aveia, pão integral) para energia sustentada","Evite cafeína em excesso (máximo 200mg/dia = 1 xícara de café)"}', 1),
((SELECT id FROM categories WHERE slug='health'), 'Sono e Descanso', 'Moon', '{"Durma de lado (esquerdo preferível) para melhorar a circulação e oxigenação do bebê","Use travesseiro entre as pernas para alinhar a pelve e aliviar dor lombar","Evite telas (celular, TV, tablet) pelo menos 1h antes de dormir","Mantenha horário regular: tente dormir e acordar no mesmo horário","Chá de camomila ou lavanda antes de dormir ajuda a relaxar","Tire cochilos de 20-30 minutos durante o dia se sentir cansaço","Crie um ambiente escuro, fresco e silencioso para dormir","Evite líquidos 2h antes de dormir para reduzir idas ao banheiro"}', 2),
((SELECT id FROM categories WHERE slug='health'), 'Saúde Emocional', 'Brain', '{"É absolutamente normal sentir ansiedade, medo e insegurança — permita-se sentir sem culpa","Converse com outras gestantes ou mães — trocar experiências alivia a pressão","Pratique meditação ou mindfulness por 10 minutos diários — apps como Calm e Headspace têm conteúdo para gestantes","Peça ajuda quando precisar — aceitar apoio não é fraqueza","Registre seus sentimentos no diário do app — escrever organiza os pensamentos","Mantenha atividades que te dão prazer e identidade além da maternidade","Se sentir tristeza persistente por mais de 2 semanas, converse com seu médico (depressão na gravidez é tratável)","Fortaleça a rede de apoio: parceiro(a), família, amigos, profissionais de saúde"}', 3),
((SELECT id FROM categories WHERE slug='health'), 'Sexualidade na Gravidez', 'Heart', '{"A libido pode variar muito durante a gravidez — aumentar, diminuir ou oscilar é normal","Sexo é seguro na maioria das gestações saudáveis e NÃO machuca o bebê","Converse abertamente com seu parceiro(a) sobre desejos, medos e limitações","Algumas posições são mais confortáveis: de lado, por cima ou de quatro apoios","O orgasmo pode causar contrações leves do útero — é normal e não prejudica o bebê","A região genital pode ficar mais sensível pelo aumento do fluxo sanguíneo","Consulte seu médico se houver sangramento após relação, contrações ou rompimento da bolsa","Intimidade não é só sexo: massagens, carícias e proximidade são igualmente importantes"}', 4),
((SELECT id FROM categories WHERE slug='health'), 'Preparação para o Parto', 'Baby', '{"Faça um plano de parto — documente suas preferências e compartilhe com a equipe médica","Prepare a mala da maternidade até a semana 36 (lista completa no app!)","Aprenda e pratique técnicas de respiração para usar durante as contrações","Visite a maternidade antes do grande dia — saber o caminho e o ambiente reduz a ansiedade","Converse com seu médico sobre tipos de parto: vaginal, cesárea, humanizado","Faça um curso de preparação para o parto (muitos hospitais oferecem gratuitamente)","Prepare um plano B: tenha alguém disponível para levar ao hospital a qualquer hora","Conheça os sinais de trabalho de parto: contrações regulares, ruptura da bolsa, perda do tampão mucoso"}', 5),
((SELECT id FROM categories WHERE slug='health'), 'Cuidados com a Pele', 'Sparkles', '{"Use protetor solar FPS 50+ todos os dias para prevenir melasma (manchas de gravidez)","Hidrate a barriga, seios e coxas 2x ao dia com óleos (amêndoas, coco, rosa mosqueta)","Evite banhos muito quentes que ressecam a pele e agravam coceiras","A acne hormonal é comum — use produtos suaves sem ácido salicílico ou retinol","A linha nigra (linha escura na barriga) é normal e desaparece após o parto","Use roupas de algodão que não irritem a pele","Beba muita água — a hidratação interna é tão importante quanto a externa","Consulte um dermatologista se surgir coceira intensa generalizada (pode indicar colestase)"}', 6),
((SELECT id FROM categories WHERE slug='health'), 'Amamentação', 'Heart', '{"Informe-se sobre amamentação ANTES do parto — conhecimento é poder!","O colostro (primeiro leite) é o alimento mais importante para o recém-nascido","Participe de grupos de apoio à amamentação durante a gravidez","Conheça as posições de amamentação: deitada, sentada, football hold","Amamentar pode ser desafiador no início — peça ajuda de consultora de lactação","Hidrate-se muito e alimente-se bem — seu corpo precisará de energia extra","Prepare mamilos com exposição ao sol por 15 minutos e aplicação de próprio leite","Não use cremes ou substâncias nos mamilos sem orientação médica"}', 7);

-- Enriched weekly tips (20 items, various weeks)
INSERT INTO public.weekly_tips (category_id, week_number, title, content, display_order) VALUES
((SELECT id FROM categories WHERE slug='journey'), 4, 'Ácido Fólico é Essencial', 'Inicie ou continue o uso de ácido fólico (400-800mcg/dia). Ele é crucial para prevenir defeitos do tubo neural do bebê. Encontrado naturalmente em espinafre, brócolis, feijão e lentilha, mas a suplementação é recomendada.', 1),
((SELECT id FROM categories WHERE slug='journey'), 6, 'Combatendo o Enjoo', 'O enjoo matinal pode ser intenso nesta fase. Estratégias que funcionam: comer biscoitos secos antes de levantar, gengibre (chá ou balas), vitamina B6, acupressura no ponto P6 (3 dedos acima do pulso).', 2),
((SELECT id FROM categories WHERE slug='journey'), 8, 'Primeira Consulta Pré-natal', 'Se ainda não fez, agende urgente sua primeira consulta pré-natal! Nela serão pedidos exames de sangue, urina, ultrassom e sorologias. Leve uma lista de perguntas — não existe dúvida boba!', 3),
((SELECT id FROM categories WHERE slug='journey'), 10, 'Proteção Solar na Gravidez', 'A pele gestante é muito sensível ao sol. Use FPS 50+ TODOS os dias, mesmo em dias nublados. O melasma (manchas escuras no rosto) pode ser evitado com proteção solar adequada.', 4),
((SELECT id FROM categories WHERE slug='journey'), 12, 'Hora de Celebrar!', 'Parabéns! O risco de aborto diminui significativamente após a 12ª semana. Este é um momento seguro para compartilhar a novidade! A translucência nucal deve ser feita entre 11 e 14 semanas.', 5),
((SELECT id FROM categories WHERE slug='journey'), 14, 'Prevenção de Estrias', 'Comece a hidratar a barriga, seios e coxas diariamente com óleos naturais (amêndoas, coco, rosa mosqueta). A hidratação não impede 100% das estrias (genética conta), mas ajuda muito!', 6),
((SELECT id FROM categories WHERE slug='journey'), 16, 'Converse com seu Bebê', 'A partir de agora o bebê pode ouvir sons! Converse, cante, leia histórias e coloque músicas para ele. Estudos mostram que bebês reconhecem a voz da mãe e músicas ouvidas na gestação.', 7),
((SELECT id FROM categories WHERE slug='journey'), 18, 'Cuidado com Tonturas', 'Levante-se sempre devagar: primeiro sente na cama, espere alguns segundos, depois levante. A hipotensão postural (queda de pressão ao levantar) é muito comum na gravidez.', 8),
((SELECT id FROM categories WHERE slug='journey'), 20, 'Ultrassom Morfológico', 'Entre 18 e 22 semanas é o período ideal para o ultrassom morfológico! Este exame avalia todas as estruturas do bebê. Se desejar, é possível descobrir o sexo do bebê neste exame.', 9),
((SELECT id FROM categories WHERE slug='journey'), 22, 'Baby Brain é Real!', 'Esquecimento e dificuldade de concentração na gravidez é real e se chama "baby brain". Não se preocupe — é temporário. Use listas, lembretes no celular e não se cobre demais.', 10),
((SELECT id FROM categories WHERE slug='journey'), 24, 'Teste de Glicose', 'Entre 24 e 28 semanas será feito o teste de tolerância à glicose (curva glicêmica) para rastrear diabetes gestacional. Siga as orientações do laboratório sobre jejum.', 11),
((SELECT id FROM categories WHERE slug='journey'), 28, 'Reta Final Começou!', 'Bem-vinda ao 3° trimestre! As consultas ficam mais frequentes (quinzenais). É hora de começar a pensar no parto, preparar a mala e fazer cursos de preparação.', 12),
((SELECT id FROM categories WHERE slug='journey'), 30, 'Posição para Dormir', 'Dormir de lado esquerdo é a posição ideal: melhora a circulação para o bebê e seus rins. Use travesseiro de corpo inteiro — pode ser o melhor investimento da gestação!', 13),
((SELECT id FROM categories WHERE slug='journey'), 32, 'Mala da Maternidade', 'Hora de preparar a mala! Para a mãe: documentos, camisolas, chinelo, absorvente, itens de higiene. Para o bebê: bodies, macacões, fraldas, mantas. Não esqueça o carregador do celular!', 14),
((SELECT id FROM categories WHERE slug='journey'), 34, 'Monitorando Movimentos', 'A partir de agora, monitore os movimentos do bebê diariamente. O ideal é sentir pelo menos 10 movimentos em 2 horas. Se notar redução, entre em contato com seu médico imediatamente.', 15),
((SELECT id FROM categories WHERE slug='journey'), 36, 'Teste Strep B', 'Entre 35 e 37 semanas será feito o teste do Streptococcus do Grupo B (Strep B). Se positivo, antibiótico será administrado durante o trabalho de parto para proteger o bebê.', 16),
((SELECT id FROM categories WHERE slug='journey'), 37, 'Sinais de Trabalho de Parto', 'Fique atenta: contrações regulares a cada 5 minutos por 1 hora, ruptura da bolsa (líquido claro escorrendo), perda do tampão mucoso com sangue. Se qualquer um ocorrer, vá à maternidade!', 17),
((SELECT id FROM categories WHERE slug='journey'), 38, 'Plano de Parto', 'Se ainda não fez, escreva seu plano de parto agora! Inclua preferências sobre: anestesia, posição para o parto, corte do cordão, contato pele a pele, amamentação na primeira hora.', 18),
((SELECT id FROM categories WHERE slug='journey'), 39, 'Paciência na Reta Final', 'O bebê nasce quando está pronto — cada dia a mais no útero é benéfico! Mantenha-se ativa com caminhadas leves, descanse bastante e confie que seu corpo sabe o que fazer.', 19),
((SELECT id FROM categories WHERE slug='journey'), 40, 'Você Está Pronta!', 'Parabéns por chegar até aqui! Confie no seu corpo, na sua preparação e na equipe médica. Cada parto é único e especial. Em breve você terá seu bebê nos braços. Você vai conseguir! 💪❤️', 20);
