// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmtrjnosuwtmulerhgnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhtdHJqbm9zdXd0bXVsZXJoZ25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0NzUzMTgsImV4cCI6MjA4ODA1MTMxOH0.6RFt5sTFctWTxb5WTDdio9WjEtQxKsHNJHlL3GmYV8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});